"""Fragments PowerShell générés pour WinPE (deploy + pilotes + unattend)."""

from __future__ import annotations


def ps_inject_drivers_lib(drivers_json: str, drivers_root: str) -> str:
    return f"""# Generated by iPXE Manager — bibliotheque pilotes + unattend (offline)
param(
    [string]$TargetOS = 'W:\\',
    [string]$DriverProfileKey = ''
)

$ErrorActionPreference = 'Continue'
$script:WinpeInjectCliMode = ($MyInvocation.InvocationName -ne '.')

$script:WinpeDriversJson = '{drivers_json}'
$script:WinpeDriversRoot = '{drivers_root}'

function Get-WinpeDriverCatalog {{
    if (-not (Test-Path -LiteralPath $script:WinpeDriversJson)) {{ return $null }}
    $raw = Get-Content -LiteralPath $script:WinpeDriversJson -Raw -ErrorAction SilentlyContinue
    if (-not $raw) {{ return $null }}
    return ($raw | ConvertFrom-Json)
}}

function Get-DriverFolderForKey {{
    param($Catalog, [string]$Key)
    if (-not $Catalog -or -not $Key) {{ return $null }}
    $meta = $Catalog.$Key
    if (-not $meta) {{ return $null }}
    if ($meta.slug) {{ return Join-Path $script:WinpeDriversRoot $meta.slug }}
    $rel = ($meta.path -replace '/', '\\').Trim('\\')
    if ($rel -match '^drivers[\\/](.+)$') {{ return Join-Path $script:WinpeDriversRoot $Matches[1] }}
    return Join-Path $script:WinpeDriversRoot $rel
}}

function Try-DetectDriverProfile {{
    param($Catalog)
    if (-not $Catalog) {{ return $null, $null, 0 }}
    $hint = ''
    try {{
        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
        if ($cs) {{ $hint = "$($cs.Manufacturer) $($cs.Model)".Trim() }}
    }} catch {{ }}
    if (-not $hint) {{ return $null, $hint, 0 }}
    $bestKey = $null
    $bestScore = 0
    foreach ($prop in $Catalog.PSObject.Properties) {{
        $k = $prop.Name
        $score = 0
        if ($hint -match [regex]::Escape($k)) {{ $score += 10 }}
        $slug = $prop.Value.slug
        if ($slug -and $hint -match [regex]::Escape($slug)) {{ $score += 8 }}
        if ($score -gt $bestScore) {{
            $bestScore = $score
            $bestKey = $k
        }}
    }}
    if ($bestScore -lt 8) {{ return $null, $hint, $bestScore }}
    return $bestKey, $hint, $bestScore
}}

function Install-WinpeDrivers {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$ProfileKey,
        [switch]$Quiet
    )
    if (-not $ProfileKey) {{
        if (-not $Quiet) {{ Write-Host 'Aucun profil pilote.' -ForegroundColor Yellow }}
        return $true
    }}
    $catalog = Get-WinpeDriverCatalog
    if (-not $catalog) {{
        if (-not $Quiet) {{ Write-Host 'drivers.json absent.' -ForegroundColor Yellow }}
        return $true
    }}
    $driverDir = Get-DriverFolderForKey $catalog $ProfileKey
    if (-not $driverDir -or -not (Test-Path -LiteralPath $driverDir)) {{
        Write-Host "Dossier pilotes introuvable : $ProfileKey" -ForegroundColor Red
        return $false
    }}
    $infCount = @(Get-ChildItem -LiteralPath $driverDir -Recurse -Filter '*.inf' -File -ErrorAction SilentlyContinue).Count
    if ($infCount -eq 0) {{
        Write-Host "Aucun .inf dans $driverDir" -ForegroundColor Red
        return $false
    }}
    if (-not $Quiet) {{
        Write-Host "Injection pilotes : $ProfileKey ($infCount .inf)" -ForegroundColor Cyan
    }}
    $imageRoot = $TargetOS.TrimEnd('\\')
    $dismArgs = @('/Image:' + $imageRoot, '/Add-Driver', '/Driver:' + $driverDir, '/Recurse')
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{
        Write-Host "DISM Add-Driver avertissement (code $($p.ExitCode)) — poursuite." -ForegroundColor Yellow
    }}
    return $true
}}

function Get-UnattendNsUri {{
    param([xml]$Doc)
    if ($Doc.DocumentElement -and $Doc.DocumentElement.NamespaceURI) {{
        return $Doc.DocumentElement.NamespaceURI
    }}
    return 'urn:schemas-microsoft-com:unattend'
}}

function Get-UnattendNsMgr {{
    param([xml]$Doc)
    $uri = Get-UnattendNsUri -Doc $Doc
    $mgr = New-Object System.Xml.XmlNamespaceManager($Doc.NameTable)
    $mgr.AddNamespace('u', $uri)
    return $mgr, $uri
}}

function New-UnattendElement {{
    param([xml]$Doc, [string]$LocalName, [string]$NsUri)
    if ($NsUri) {{ return $Doc.CreateElement($LocalName, $NsUri) }}
    return $Doc.CreateElement($LocalName)
}}

function Get-ShellSetupComponentsForPass {{
    param([xml]$Doc, [string]$Pass, $NsMgr)
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']", $NsMgr)
    if (-not $settings) {{ return @() }}
    return @($settings.SelectNodes('u:component[@name="Microsoft-Windows-Shell-Setup"]', $NsMgr))
}}

function Get-ShellSetupTemplateAttrs {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $ref = $Doc.SelectSingleNode('//u:component[@name="Microsoft-Windows-Shell-Setup"]', $NsMgr)
    if ($ref) {{
        return @{{
            processorArchitecture = $ref.GetAttribute('processorArchitecture')
            publicKeyToken = $ref.GetAttribute('publicKeyToken')
            language = $ref.GetAttribute('language')
            versionScope = $ref.GetAttribute('versionScope')
        }}
    }}
    return @{{
        processorArchitecture = 'amd64'
        publicKeyToken = '31bf3856ad364e35'
        language = 'neutral'
        versionScope = 'nonSxS'
    }}
}}

function Ensure-ShellSetupForPass {{
    param([xml]$Doc, [string]$Pass, $NsMgr, [string]$NsUri)
    $shells = Get-ShellSetupComponentsForPass -Doc $Doc -Pass $Pass -NsMgr $NsMgr
    if ($shells.Count -gt 0) {{ return $shells[0] }}
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']", $NsMgr)
    if (-not $settings) {{
        $settings = New-UnattendElement -Doc $Doc -LocalName 'settings' -NsUri $NsUri
        $null = $settings.SetAttribute('pass', $Pass)
        $Doc.DocumentElement.AppendChild($settings) | Out-Null
    }}
    $attrs = Get-ShellSetupTemplateAttrs -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    $shell = New-UnattendElement -Doc $Doc -LocalName 'component' -NsUri $NsUri
    $null = $shell.SetAttribute('name', 'Microsoft-Windows-Shell-Setup')
    foreach ($k in $attrs.Keys) {{
        if ($attrs[$k]) {{ $null = $shell.SetAttribute($k, $attrs[$k]) }}
    }}
    $settings.AppendChild($shell) | Out-Null
    return $shell
}}

function Set-UnattendXmlText {{
    param($Parent, [xml]$Doc, $NsMgr, [string]$NsUri, [string]$LocalName, [string]$Value)
    $node = $Parent.SelectSingleNode("u:$LocalName", $NsMgr)
    if (-not $node) {{
        $node = New-UnattendElement -Doc $Doc -LocalName $LocalName -NsUri $NsUri
        $null = $Parent.AppendChild($node)
    }}
    $node.InnerText = $Value
    return $node
}}

function Set-UnattendPasswordNode {{
    param($Parent, [xml]$Doc, $NsMgr, [string]$NsUri, [string]$Password, [switch]$AsPlainText)
    $pwEl = $Parent.SelectSingleNode('u:Password', $NsMgr)
    if (-not $pwEl) {{
        $pwEl = New-UnattendElement -Doc $Doc -LocalName 'Password' -NsUri $NsUri
        $null = $Parent.AppendChild($pwEl)
    }}
    if ($AsPlainText) {{
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'Value' -Value $Password | Out-Null
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'PlainText' -Value 'true' | Out-Null
    }} else {{
        $blob = ConvertTo-UnattendPasswordBlob -PlainText $Password
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'Value' -Value $blob | Out-Null
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'PlainText' -Value 'false' | Out-Null
    }}
}}

function Set-UnattendComputerName {{
    param([xml]$Doc, $NsMgr, [string]$NsUri, [string]$ComputerName)
    $updated = 0
    foreach ($pass in @('specialize', 'generalize')) {{
        $nodes = $Doc.SelectNodes("//u:settings[@pass='$pass']//u:ComputerName", $NsMgr)
        foreach ($n in @($nodes)) {{
            $n.InnerText = $ComputerName
            $updated++
        }}
    }}
    if ($updated -eq 0) {{
        $shell = Ensure-ShellSetupForPass -Doc $Doc -Pass 'specialize' -NsMgr $NsMgr -NsUri $NsUri
        Set-UnattendXmlText -Parent $shell -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'ComputerName' -Value $ComputerName | Out-Null
        $updated = 1
    }}
    return $updated
}}

function Set-UnattendLocalAccount {{
    param([xml]$Doc, $Shell, $NsMgr, [string]$NsUri, [string]$User, [string]$Password)
    $userAccounts = $Shell.SelectSingleNode('u:UserAccounts', $NsMgr)
    if (-not $userAccounts) {{
        $userAccounts = New-UnattendElement -Doc $Doc -LocalName 'UserAccounts' -NsUri $NsUri
        $Shell.AppendChild($userAccounts) | Out-Null
    }}
    $localAccounts = $userAccounts.SelectSingleNode('u:LocalAccounts', $NsMgr)
    if (-not $localAccounts) {{
        $localAccounts = New-UnattendElement -Doc $Doc -LocalName 'LocalAccounts' -NsUri $NsUri
        $userAccounts.AppendChild($localAccounts) | Out-Null
    }}
    $acct = $null
    foreach ($node in @($localAccounts.SelectNodes('u:LocalAccount', $NsMgr))) {{
        $n = $node.SelectSingleNode('u:Name', $NsMgr)
        if ($n -and $n.InnerText -eq $User) {{ $acct = $node; break }}
    }}
    if (-not $acct) {{
        $existing = @($localAccounts.SelectNodes('u:LocalAccount', $NsMgr))
        if ($existing.Count -eq 1) {{
            $acct = $existing[0]
            Write-Host 'Mise a jour du compte local existant du master.' -ForegroundColor Gray
        }} else {{
            $acct = New-UnattendElement -Doc $Doc -LocalName 'LocalAccount' -NsUri $NsUri
            $localAccounts.AppendChild($acct) | Out-Null
        }}
    }}
    Set-UnattendPasswordNode -Parent $acct -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -Password $Password
    Set-UnattendXmlText -Parent $acct -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'DisplayName' -Value $User | Out-Null
    Set-UnattendXmlText -Parent $acct -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'Group' -Value 'Administrators' | Out-Null
    Set-UnattendXmlText -Parent $acct -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -LocalName 'Name' -Value $User | Out-Null
}}

function Set-UnattendAdministratorPassword {{
    param([xml]$Doc, $Shell, $NsMgr, [string]$NsUri, [string]$Password)
    Set-UnattendPasswordNode -Parent $Shell -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -Password $Password
}}

function Save-UnattendDocument {{
    param([xml]$Doc, [string]$Path)
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Encoding = New-Object System.Text.UTF8Encoding $true
    $settings.Indent = $true
    $settings.OmitXmlDeclaration = $false
    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try {{ $Doc.Save($writer) }} finally {{ $writer.Close() }}
}}

function ConvertTo-UnattendPasswordBlob {{
    param([string]$PlainText)
    if (-not $PlainText) {{ return '' }}
    $bytes = [System.Text.Encoding]::Unicode.GetBytes($PlainText)
    return [Convert]::ToBase64String($bytes)
}}

function Find-OfflineUnattendPath {{
    param([string]$TargetOS = 'W:\\')
    $candidates = @(
        (Join-Path $TargetOS 'Windows\\Panther\\unattend.xml'),
        (Join-Path $TargetOS 'Windows\\System32\\Sysprep\\unattend.xml'),
        (Join-Path $TargetOS 'unattend.xml')
    )
    foreach ($p in $candidates) {{
        if (Test-Path -LiteralPath $p) {{ return $p }}
    }}
    $found = @(Get-ChildItem -LiteralPath $TargetOS -Recurse -Filter 'unattend.xml' -File -ErrorAction SilentlyContinue | Select-Object -First 1)
    if ($found) {{ return $found.FullName }}
    return $null
}}

function Update-OfflineUnattend {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$ComputerName = '',
        [string]$LocalUser = '',
        [string]$LocalPassword = ''
    )
    $path = Find-OfflineUnattendPath -TargetOS $TargetOS
    if (-not $path) {{
        Write-Host 'unattend.xml introuvable dans l image — nom machine / user non modifies.' -ForegroundColor Yellow
        return $false
    }}
    Write-Host "Personnalisation : $path" -ForegroundColor Cyan
    [xml]$doc = Get-Content -LiteralPath $path -Encoding UTF8
    $nsMgr, $nsUri = Get-UnattendNsMgr -Doc $doc
    $changed = $false

    if ($ComputerName -and $ComputerName.Trim()) {{
        $cn = $ComputerName.Trim()
        if ($cn.Length -gt 15) {{ $cn = $cn.Substring(0, 15) }}
        $cn = $cn -replace '[^a-zA-Z0-9\\-]', ''
        if ($cn) {{
            $n = Set-UnattendComputerName -Doc $doc -NsMgr $nsMgr -NsUri $nsUri -ComputerName $cn
            Write-Host "Nom machine : $cn ($n emplacement(s) mis a jour dans le XML du master)" -ForegroundColor Green
            $changed = $true
        }}
    }}

    if ($LocalUser -and $LocalUser.Trim()) {{
        $user = $LocalUser.Trim() -replace '[^a-zA-Z0-9._-]', ''
        if (-not $user) {{
            Write-Host 'Nom utilisateur invalide — compte local ignore.' -ForegroundColor Yellow
        }} elseif (-not $LocalPassword) {{
            Write-Host 'Mot de passe requis pour un compte local — compte ignore (cochez et saisissez un mot de passe).' -ForegroundColor Yellow
        }} else {{
            $shellOobe = (Get-ShellSetupComponentsForPass -Doc $doc -Pass 'oobeSystem' -NsMgr $nsMgr | Select-Object -First 1)
            if ($shellOobe) {{
                $hasLocal = $shellOobe.SelectSingleNode('.//u:LocalAccounts/u:LocalAccount', $nsMgr)
                if ($hasLocal) {{
                    Set-UnattendLocalAccount -Doc $doc -Shell $shellOobe -NsMgr $nsMgr -NsUri $nsUri -User $user -Password $LocalPassword
                    Write-Host "Compte local (oobeSystem, XML master) : $user" -ForegroundColor Green
                }} elseif ($shellOobe.SelectSingleNode('u:AdministratorPassword', $nsMgr)) {{
                    Set-UnattendAdministratorPassword -Doc $doc -Shell $shellOobe -NsMgr $nsMgr -NsUri $nsUri -Password $LocalPassword
                    Write-Host 'Mot de passe administrateur (AdministratorPassword) mis a jour.' -ForegroundColor Green
                }} else {{
                    Set-UnattendLocalAccount -Doc $doc -Shell $shellOobe -NsMgr $nsMgr -NsUri $nsUri -User $user -Password $LocalPassword
                    Write-Host "Compte local ajoute dans oobeSystem existant : $user" -ForegroundColor Green
                }}
                $changed = $true
            }} else {{
                Write-Host 'Pas de bloc oobeSystem / Shell-Setup dans le master — compte non ajoute (evite de casser le XML).' -ForegroundColor Yellow
                Write-Host 'Astuce : definissez le compte dans le unattend.xml du master, ou cochez seulement le nom machine.' -ForegroundColor Gray
            }}
        }}
    }}

    if ($changed) {{
        Save-UnattendDocument -Doc $doc -Path $path
    }} else {{
        Write-Host 'Aucune modification unattend (valeurs par defaut du master).' -ForegroundColor Gray
    }}
    return $true
}}

if ($script:WinpeInjectCliMode) {{
    if ($DriverProfileKey) {{
        $ok = Install-WinpeDrivers -TargetOS $TargetOS -ProfileKey $DriverProfileKey
        if (-not $ok) {{ exit 1 }}
    }}
    exit 0
}}
"""


def ps_deploy_wizard(scripts_root: str, masters_file: str) -> str:
    return f"""# Generated by iPXE Manager — assistant de deploiement WinPE
$ErrorActionPreference = 'Stop'
$ScriptsRoot = '{scripts_root}'
$MastersFile = Join-Path $ScriptsRoot '{masters_file}'
$TargetOS    = 'W:\\'
$TargetWin   = 'W:\\Windows'

$injectLib = Join-Path $ScriptsRoot 'inject-drivers.ps1'
if (-not (Test-Path -LiteralPath $injectLib)) {{
    Write-Host "Bibliotheque introuvable : $injectLib" -ForegroundColor Red
    Pause; exit 1
}}
. $injectLib

function Test-WinpeGuiAvailable {{
    try {{
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
        Add-Type -AssemblyName System.Drawing -ErrorAction Stop
        return $true
    }} catch {{ return $false }}
}}

function Show-ConsoleDeployWizard {{
    param($Masters, $Catalog, $AutoDriverKey, $DriverHint)
    Clear-Host
    Write-Host '=== iPXE Manager — Deploiement (console) ===' -ForegroundColor Cyan
    for ($i = 0; $i -lt $Masters.Count; $i++) {{
        Write-Host "[$($i+1)] $($Masters[$i].label) ($($Masters[$i].slug))"
    }}
    $mIdx = 0
    while ($true) {{
        $c = Read-Host 'Master'
        if ([int]::TryParse($c, [ref]$mIdx) -and $mIdx -ge 1 -and $mIdx -le $Masters.Count) {{ break }}
        Write-Host 'Choix invalide.' -ForegroundColor Red
    }}
    $master = $Masters[$mIdx - 1]
    $driverKey = $AutoDriverKey
    if (-not $driverKey -and $Catalog) {{
        Write-Host "Machine non reconnue ($DriverHint). Choisissez un profil pilotes." -ForegroundColor Yellow
        $keys = @($Catalog.PSObject.Properties.Name | Sort-Object)
        for ($j = 0; $j -lt $keys.Count; $j++) {{ Write-Host "[$($j+1)] $($keys[$j])" }}
        Write-Host '[0] Aucun pilote'
        $dIdx = -1
        while ($true) {{
            $dc = Read-Host 'Profil pilotes'
            if ($dc -eq '0') {{ $driverKey = $null; break }}
            if ([int]::TryParse($dc, [ref]$dIdx) -and $dIdx -ge 1 -and $dIdx -le $keys.Count) {{
                $driverKey = $keys[$dIdx - 1]; break
            }}
        }}
    }}
    $cn = Read-Host 'Nom machine (Entree = defaut master)'
    $addUser = Read-Host 'Ajouter un utilisateur local ? (O/N)'
    $lu = ''; $lp = ''
    if ($addUser -match '^[oOyY]') {{
        $lu = Read-Host 'Nom utilisateur'
        while (-not $lp) {{
            $lp = Read-Host 'Mot de passe (obligatoire)'
            if (-not $lp) {{ Write-Host 'Mot de passe requis.' -ForegroundColor Red }}
        }}
    }}
    return [pscustomobject]@{{
        Master = $master
        DriverProfileKey = $driverKey
        ComputerName = $cn
        LocalUser = $lu
        LocalPassword = $lp
    }}
}}

function Show-WinpeDeployWizard {{
    param($Masters, $Catalog, $AutoDriverKey, $DriverHint, $RequireManualDriver)
    if (-not (Test-WinpeGuiAvailable)) {{
        return Show-ConsoleDeployWizard -Masters $Masters -Catalog $Catalog -AutoDriverKey $AutoDriverKey -DriverHint $DriverHint
    }}
    Add-Type -AssemblyName System.Windows.Forms
    Add-Type -AssemblyName System.Drawing

    $form = New-Object System.Windows.Forms.Form
    $form.Text = 'iPXE Manager — Deploiement'
    $form.Size = New-Object System.Drawing.Size(520, 580)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false

    $lblM = New-Object System.Windows.Forms.Label
    $lblM.Text = 'Master (image Windows)'
    $lblM.Location = New-Object System.Drawing.Point(12, 12)
    $lblM.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblM)

    $lstM = New-Object System.Windows.Forms.ListBox
    $lstM.Location = New-Object System.Drawing.Point(12, 34)
    $lstM.Size = New-Object System.Drawing.Size(480, 100)
    foreach ($m in $Masters) {{ [void]$lstM.Items.Add("$($m.label)  [$($m.slug)]") }}
    if ($lstM.Items.Count -gt 0) {{ $lstM.SelectedIndex = 0 }}
    $form.Controls.Add($lstM)

    $lblD = New-Object System.Windows.Forms.Label
    if ($RequireManualDriver) {{
        $lblD.Text = 'La machine n''a pas ete reconnue. Veuillez choisir les pilotes souhaites.'
        $lblD.ForeColor = [System.Drawing.Color]::DarkOrange
    }} elseif ($AutoDriverKey) {{
        $lblD.Text = "Pilotes : profil « $AutoDriverKey » detecte automatiquement."
        $lblD.ForeColor = [System.Drawing.Color]::DarkGreen
    }} else {{
        $lblD.Text = 'Pilotes (optionnel)'
    }}
    $lblD.Location = New-Object System.Drawing.Point(12, 142)
    $lblD.Size = New-Object System.Drawing.Size(480, 36)
    $form.Controls.Add($lblD)

    $cmbD = New-Object System.Windows.Forms.ComboBox
    $cmbD.Location = New-Object System.Drawing.Point(12, 180)
    $cmbD.Size = New-Object System.Drawing.Size(480, 24)
    $cmbD.DropDownStyle = 'DropDownList'
    [void]$cmbD.Items.Add('(aucun pilote)')
    if ($Catalog) {{
        foreach ($k in ($Catalog.PSObject.Properties.Name | Sort-Object)) {{ [void]$cmbD.Items.Add($k) }}
    }}
    if ($AutoDriverKey -and $cmbD.Items.Contains($AutoDriverKey)) {{
        $cmbD.SelectedItem = $AutoDriverKey
    }} else {{
        $cmbD.SelectedIndex = 0
    }}
    $form.Controls.Add($cmbD)

    $lblCn = New-Object System.Windows.Forms.Label
    $lblCn.Text = 'Nom de la machine (vide = defaut du master)'
    $lblCn.Location = New-Object System.Drawing.Point(12, 218)
    $lblCn.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblCn)

    $txtCn = New-Object System.Windows.Forms.TextBox
    $txtCn.Location = New-Object System.Drawing.Point(12, 240)
    $txtCn.Size = New-Object System.Drawing.Size(480, 24)
    $form.Controls.Add($txtCn)

    $chkU = New-Object System.Windows.Forms.CheckBox
    $chkU.Text = 'Ajouter un utilisateur local (en plus du master)'
    $chkU.Location = New-Object System.Drawing.Point(12, 278)
    $chkU.Size = New-Object System.Drawing.Size(480, 24)
    $form.Controls.Add($chkU)

    $lblU = New-Object System.Windows.Forms.Label
    $lblU.Text = 'Nom utilisateur'
    $lblU.Location = New-Object System.Drawing.Point(12, 306)
    $lblU.Size = New-Object System.Drawing.Size(200, 20)
    $form.Controls.Add($lblU)

    $txtU = New-Object System.Windows.Forms.TextBox
    $txtU.Location = New-Object System.Drawing.Point(12, 326)
    $txtU.Size = New-Object System.Drawing.Size(480, 24)
    $txtU.Enabled = $false
    $form.Controls.Add($txtU)

    $lblP = New-Object System.Windows.Forms.Label
    $lblP.Text = 'Mot de passe'
    $lblP.Location = New-Object System.Drawing.Point(12, 354)
    $lblP.Size = New-Object System.Drawing.Size(200, 20)
    $form.Controls.Add($lblP)

    $txtP = New-Object System.Windows.Forms.TextBox
    $txtP.Location = New-Object System.Drawing.Point(12, 374)
    $txtP.Size = New-Object System.Drawing.Size(480, 24)
    $txtP.UseSystemPasswordChar = $true
    $txtP.Enabled = $false
    $form.Controls.Add($txtP)

    $chkU.Add_CheckedChanged({{
        $en = $chkU.Checked
        $txtU.Enabled = $en
        $txtP.Enabled = $en
    }})

    $btnOk = New-Object System.Windows.Forms.Button
    $btnOk.Text = 'Deployer'
    $btnOk.Location = New-Object System.Drawing.Point(12, 420)
    $btnOk.Size = New-Object System.Drawing.Size(230, 36)
    $btnOk.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.AcceptButton = $btnOk
    $form.Controls.Add($btnOk)

    $btnCancel = New-Object System.Windows.Forms.Button
    $btnCancel.Text = 'Annuler'
    $btnCancel.Location = New-Object System.Drawing.Point(262, 420)
    $btnCancel.Size = New-Object System.Drawing.Size(230, 36)
    $btnCancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
    $form.CancelButton = $btnCancel
    $form.Controls.Add($btnCancel)

    $result = $form.ShowDialog()
    if ($result -ne [System.Windows.Forms.DialogResult]::OK) {{ return $null }}
    if ($chkU.Checked) {{
        if (-not $txtU.Text.Trim()) {{
            [System.Windows.Forms.MessageBox]::Show('Indiquez un nom d utilisateur.', 'Deploiement', 'OK', 'Warning') | Out-Null
            return $null
        }}
        if (-not $txtP.Text) {{
            [System.Windows.Forms.MessageBox]::Show('Un mot de passe est obligatoire pour creer un compte local.', 'Deploiement', 'OK', 'Warning') | Out-Null
            return $null
        }}
    }}
    if ($lstM.SelectedIndex -lt 0) {{ return $null }}
    $master = $Masters[$lstM.SelectedIndex]
    $driverKey = $null
    if ($cmbD.SelectedItem -and $cmbD.SelectedItem -ne '(aucun pilote)') {{
        $driverKey = [string]$cmbD.SelectedItem
    }}
    $lu = ''; $lp = ''
    if ($chkU.Checked) {{
        $lu = $txtU.Text.Trim()
        $lp = $txtP.Text
    }}
    return [pscustomobject]@{{
        Master = $master
        DriverProfileKey = $driverKey
        ComputerName = $txtCn.Text.Trim()
        LocalUser = $lu
        LocalPassword = $lp
    }}
}}

function Invoke-WinpeDeployment {{
    param($Choice)
    $wimPath = $Choice.Master.wimPath
    $dismIdx = [int]$Choice.Master.dismIndex
    if (-not (Test-Path -LiteralPath $wimPath)) {{
        throw "install.wim introuvable : $wimPath"
    }}
    Write-Host '' 
    Write-Host "Deploiement : $($Choice.Master.label)" -ForegroundColor Green
    Write-Host 'Application de l image (DISM)...' -ForegroundColor Cyan
    $dismArgs = @('/Apply-Image', "/ImageFile:$wimPath", "/Index:$dismIdx", "/ApplyDir:$TargetOS", '/CheckIntegrity', '/Verify')
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{ throw 'DISM /Apply-Image a echoue.' }}
    Write-Host 'Image appliquee.' -ForegroundColor Green

    Install-WinpeDrivers -TargetOS $TargetOS -ProfileKey $Choice.DriverProfileKey -Quiet | Out-Null

    Update-OfflineUnattend -TargetOS $TargetOS -ComputerName $Choice.ComputerName -LocalUser $Choice.LocalUser -LocalPassword $Choice.LocalPassword | Out-Null

    Write-Host 'Configuration demarrage UEFI (bcdboot)...' -ForegroundColor Cyan
    $p2 = Start-Process -FilePath 'bcdboot.exe' -ArgumentList @("$TargetWin", '/s', 'S:', '/f', 'uefi') -Wait -PassThru -NoNewWindow
    if ($p2.ExitCode -ne 0) {{ throw 'bcdboot a echoue.' }}

    Write-Host 'Redemarrage dans 10 secondes...' -ForegroundColor Green
    Start-Sleep -Seconds 10
    wpeutil reboot
}}

# --- Main ---
if (-not (Test-Path -LiteralPath $MastersFile)) {{
    Write-Host "masters.json introuvable : $MastersFile" -ForegroundColor Red
    Pause; exit 1
}}
$masters = @(Get-Content -LiteralPath $MastersFile -Raw | ConvertFrom-Json)
if (-not $masters -or $masters.Count -eq 0) {{
    Write-Host 'Aucun master.' -ForegroundColor Red
    Pause; exit 1
}}

$catalog = Get-WinpeDriverCatalog
$autoKey, $hint, $score = Try-DetectDriverProfile -Catalog $catalog
$requireManual = -not $autoKey

$choice = Show-WinpeDeployWizard -Masters $masters -Catalog $catalog -AutoDriverKey $autoKey -DriverHint $hint -RequireManualDriver $requireManual
if (-not $choice) {{
    Write-Host 'Operation annulee.' -ForegroundColor Yellow
    exit 1
}}

try {{
    Invoke-WinpeDeployment -Choice $choice
}} catch {{
    Write-Host $_.Exception.Message -ForegroundColor Red
    Pause
    exit 1
}}
"""
