"""
Génération des scripts WinPE (PowerShell + startnet.cmd minimal) sur le partage HTTP/SMB.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path

from app.config import settings
from app.models.models import IsoVersion, WinpeInstall
from app.services.winpe_installs import (
    INSTALL_WIM_FILENAME,
    install_wim_path,
    installs_root,
    smb_connect_host_for_winpe,
    smb_host_from_settings,
    smb_share_name,
    version_segment,
)
from app.services.winpe_wim import (
    STARTNET_WIM_PATH,
    boot_wim_filesystem_path,
    run_wimupdate_add,
)

logger = logging.getLogger(__name__)

SCRIPTS_DIRNAME = "scripts"
DEPLOY_PS1 = "deploy.ps1"
INJECT_DRIVERS_PS1 = "inject-drivers.ps1"
MASTERS_JSON = "masters.json"


def scripts_dir(version: IsoVersion) -> Path:
    os_slug = version.os_type.slug
    seg = version_segment(version)
    path = settings.boot_dir / os_slug / seg / SCRIPTS_DIRNAME
    path.mkdir(parents=True, exist_ok=True)
    return path


def z_boot_prefix(version: IsoVersion) -> str:
    """Préfixe sous le lecteur Z: (racine = partage [boot])."""
    os_slug = version.os_type.slug
    seg = version_segment(version)
    return f"{os_slug}\\{seg}"


def z_scripts_dir(version: IsoVersion) -> str:
    return f"Z:\\{z_boot_prefix(version)}\\{SCRIPTS_DIRNAME}"


def z_drivers_root() -> str:
    return "Z:\\drivers"


def build_masters_catalog(
    version: IsoVersion, installs: list[WinpeInstall]
) -> list[dict]:
    prefix = z_boot_prefix(version)
    rows: list[dict] = []
    for wi in sorted(installs, key=lambda x: (x.label or x.slug).lower()):
        if not install_wim_path(version, wi.slug).is_file():
            continue
        rows.append(
            {
                "slug": wi.slug,
                "label": (wi.label or wi.slug).strip() or wi.slug,
                "wimPath": f"Z:\\{prefix}\\installs\\{wi.slug}\\{INSTALL_WIM_FILENAME}",
                "dismIndex": max(1, int(wi.wim_index or 1)),
            }
        )
    return rows


def generate_masters_json(version: IsoVersion, installs: list[WinpeInstall]) -> str:
    return json.dumps(build_masters_catalog(version, installs), ensure_ascii=False, indent=2)


def generate_deploy_ps1(version: IsoVersion) -> str:
    scripts = z_scripts_dir(version)
    return f"""# Generated by iPXE Manager — {version.version_label or version.id}
# Ne pas modifier à la main : régénérer depuis l'interface (scripts WinPE).

$ErrorActionPreference = 'Stop'
$BootDrive   = 'Z:'
$ScriptsRoot = '{scripts}'
$MastersFile = Join-Path $ScriptsRoot '{MASTERS_JSON}'
$TargetOS    = 'W:\\'
$TargetWin   = 'W:\\Windows'

function Get-MasterSelection {{
    Clear-Host
    Write-Host '===================================================' -ForegroundColor Cyan
    Write-Host '             SELECTION DU MASTER A DEPLOYER        ' -ForegroundColor Cyan
    Write-Host '===================================================' -ForegroundColor Cyan
    Write-Host ''

    if (-not (Test-Path -LiteralPath $MastersFile)) {{
        Write-Host "Fichier introuvable : $MastersFile" -ForegroundColor Red
        return $null
    }}
    $masters = Get-Content -LiteralPath $MastersFile -Raw | ConvertFrom-Json
    if (-not $masters -or $masters.Count -eq 0) {{
        Write-Host 'Aucun master (install.wim) dans masters.json.' -ForegroundColor Red
        return $null
    }}

    for ($i = 0; $i -lt $masters.Count; $i++) {{
        $m = $masters[$i]
        $num = $i + 1
        Write-Host "[$num] - $($m.label) ($($m.slug))" 
    }}
    Write-Host ''
    Write-Host '[Q] - Quitter' -ForegroundColor Yellow
    Write-Host ''

    while ($true) {{
        $choice = Read-Host 'Entrez le numero du Master'
        if ($choice -match '^[qQ]$') {{ return 'QUIT' }}
        $idx = 0
        if ([int]::TryParse($choice, [ref]$idx) -and $idx -ge 1 -and $idx -le $masters.Count) {{
            return $masters[$idx - 1]
        }}
        Write-Host 'Choix invalide.' -ForegroundColor Red
    }}
}}

$selected = Get-MasterSelection
if ($selected -eq 'QUIT' -or -not $selected) {{
    Write-Host 'Operation annulee.' -ForegroundColor Yellow
    exit 1
}}

$wimPath = $selected.wimPath
$dismIdx = [int]$selected.dismIndex
if (-not (Test-Path -LiteralPath $wimPath)) {{
    Write-Host "install.wim introuvable : $wimPath" -ForegroundColor Red
    Pause
    exit 1
}}

Write-Host ''
Write-Host "Master selectionne : $($selected.label)" -ForegroundColor Green
Write-Host "Image : $wimPath (index DISM $dismIdx)" -ForegroundColor Green
Write-Host "Cible : $TargetOS" -ForegroundColor Yellow
Pause

Write-Host 'Application de l image (DISM)...' -ForegroundColor Cyan
$dismArgs = @(
    '/Apply-Image',
    "/ImageFile:$wimPath",
    "/Index:$dismIdx",
    "/ApplyDir:$TargetOS",
    '/CheckIntegrity',
    '/Verify'
)
$p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
if ($p.ExitCode -ne 0) {{
    Write-Host 'DISM /Apply-Image a echoue.' -ForegroundColor Red
    Pause
    exit 1
}}
Write-Host 'Master applique avec succes.' -ForegroundColor Green

$injectScript = Join-Path $ScriptsRoot '{INJECT_DRIVERS_PS1}'
if (Test-Path -LiteralPath $injectScript) {{
    Write-Host 'Injection des pilotes...' -ForegroundColor Cyan
    & $injectScript -TargetOS $TargetOS
    if ($LASTEXITCODE -ne 0) {{
        Write-Host 'Injection pilotes terminee avec avertissements ou erreur.' -ForegroundColor Yellow
    }}
}} else {{
    Write-Host "Script pilotes absent : $injectScript" -ForegroundColor Yellow
}}

Write-Host 'Configuration demarrage UEFI (bcdboot)...' -ForegroundColor Cyan
$p2 = Start-Process -FilePath 'bcdboot.exe' -ArgumentList @("$TargetWin", '/s', 'S:', '/f', 'uefi') -Wait -PassThru -NoNewWindow
if ($p2.ExitCode -ne 0) {{
    Write-Host 'bcdboot a echoue.' -ForegroundColor Red
    Pause
    exit 1
}}

Write-Host 'Redemarrage dans 10 secondes...' -ForegroundColor Green
Start-Sleep -Seconds 10
wpeutil reboot
"""


def generate_inject_drivers_ps1(version: IsoVersion) -> str:
    drivers_json = f"{z_drivers_root()}\\drivers.json"
    return f"""# Generated by iPXE Manager — injection pilotes
param(
    [string]$TargetOS = 'W:\\'
)

$ErrorActionPreference = 'Continue'
$DriversJson = '{drivers_json}'
$DriversRoot = '{z_drivers_root()}'
$TargetWin   = Join-Path $TargetOS 'Windows'

function Show-DriverMenu {{
    param($Catalog)
    Clear-Host
    Write-Host '===================================================' -ForegroundColor Cyan
    Write-Host '        SELECTION MANUELLE DU PROFIL PILOTES       ' -ForegroundColor Cyan
    Write-Host '===================================================' -ForegroundColor Cyan
    $keys = @($Catalog.PSObject.Properties.Name | Sort-Object)
    $i = 1
    $map = @{{}}
    foreach ($k in $keys) {{
        $meta = $Catalog.$k
        $cnt = if ($meta.count) {{ $meta.count }} else {{ '?' }}
        Write-Host "[$i] $k ($cnt fichiers) - $($meta.path)"
        $map[$i] = $k
        $i++
    }}
    Write-Host '[Q] Quitter sans installer de pilotes'
    while ($true) {{
        $c = Read-Host 'Choix'
        if ($c -match '^[qQ]$') {{ return $null }}
        $n = 0
        if ([int]::TryParse($c, [ref]$n) -and $map.ContainsKey($n)) {{
            return $map[$n]
        }}
        Write-Host 'Choix invalide.' -ForegroundColor Red
    }}
}}

function Get-DriverFolderForKey {{
    param($Catalog, [string]$Key)
    $meta = $Catalog.$Key
    if (-not $meta) {{ return $null }}
    if ($meta.slug) {{
        return Join-Path $DriversRoot $meta.slug
    }}
    $rel = ($meta.path -replace '/', '\\').Trim('\\')
    if ($rel -match '^drivers[\\/](.+)$') {{ return Join-Path $DriversRoot $Matches[1] }}
    return Join-Path $DriversRoot $rel
}}

function Try-DetectDriverProfile {{
    param($Catalog)
    $hint = ''
    try {{
        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
        if ($cs) {{
            $hint = "$($cs.Manufacturer) $($cs.Model)"
        }}
    }} catch {{ }}
    if (-not $hint) {{ return $null, $null }}
    Write-Host "Detection materielle : $hint" -ForegroundColor Cyan
    $bestKey = $null
    $bestScore = 0
    foreach ($prop in $Catalog.PSObject.Properties) {{
        $k = $prop.Name
        $score = 0
        if ($hint -match [regex]::Escape($k)) {{ $score += 10 }}
        $slug = $prop.Value.slug
        if ($slug -and $hint -match [regex]::Escape($slug)) {{ $score += 8 }}
        if ($score -gt $bestScore) {{
            $bestScore = $score
            $bestKey = $k
        }}
    }}
    return $bestKey, $hint
}}

if (-not (Test-Path -LiteralPath $DriversJson)) {{
    Write-Host 'drivers.json absent — pilotes ignores.' -ForegroundColor Yellow
    exit 0
}}

$catalog = Get-Content -LiteralPath $DriversJson -Raw | ConvertFrom-Json
if (-not $catalog) {{
    Write-Host 'Catalogue pilotes vide.' -ForegroundColor Yellow
    exit 0
}}

$profileKey = $null
$detected, $hint = Try-DetectDriverProfile $catalog
if ($detected) {{
    Write-Host "Profil propose : $detected" -ForegroundColor Green
    $confirm = Read-Host 'Utiliser ce profil ? (O/N, Entree=O)'
    if ($confirm -eq '' -or $confirm -match '^[oOyY]') {{
        $profileKey = $detected
    }}
}}

while (-not $profileKey) {{
    $profileKey = Show-DriverMenu $catalog
    if (-not $profileKey) {{
        Write-Host 'Aucun pilote installe.' -ForegroundColor Yellow
        exit 0
    }}
}}

$driverDir = Get-DriverFolderForKey $catalog $profileKey
if (-not $driverDir -or -not (Test-Path -LiteralPath $driverDir)) {{
    Write-Host "Dossier pilotes introuvable pour $profileKey" -ForegroundColor Red
    Write-Host "Verifiez Z:\\drivers\\ et drivers.json sur le serveur." -ForegroundColor Yellow
    exit 1
}}

$infFiles = @(Get-ChildItem -LiteralPath $driverDir -Recurse -Filter '*.inf' -File -ErrorAction SilentlyContinue)
if ($infFiles.Count -eq 0) {{
    Write-Host "Aucun fichier .inf dans : $driverDir" -ForegroundColor Red
    Write-Host "DISM /Add-Driver exige des paquets pilotes (.inf + .sys/.cat)." -ForegroundColor Yellow
    Write-Host "Uploadez les pilotes extraits (dossier avec des .inf) via iPXE Manager." -ForegroundColor Yellow
    exit 1
}}

Write-Host "Installation pilotes : $profileKey" -ForegroundColor Cyan
Write-Host "Source : $driverDir ($($infFiles.Count) fichier(s) .inf)" -ForegroundColor Cyan
Write-Host "Cible image offline : $TargetOS" -ForegroundColor Cyan

# Paquets souvent inutiles en VM classique ou qui echouent hors ligne (ex. viosock = vsock)
$optionalSkip = @('viosock.inf', 'viosock_amd64.inf')

$imageRoot = $TargetOS.TrimEnd('\\')
$ok = 0
$fail = 0
$skip = 0
foreach ($inf in $infFiles) {{
    $name = $inf.Name
    if ($optionalSkip -contains $name.ToLower()) {{
        Write-Host "  [ignore] $name (pilote optionnel, non requis pour le boot)" -ForegroundColor DarkGray
        $skip++
        continue
    }}
    Write-Host "  -> $name" -ForegroundColor Gray
    $dismArgs = @(
        '/Image:' + $imageRoot,
        '/Add-Driver',
        '/Driver:' + $inf.FullName
    )
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -eq 0) {{
        $ok++
    }} else {{
        Write-Host "     echec DISM code $($p.ExitCode) pour $name (souvent non applicable a cette VM)" -ForegroundColor Yellow
        $fail++
    }}
}}

Write-Host "Bilan pilotes : $ok OK, $fail echec(s), $skip ignore(s)." -ForegroundColor Cyan
if ($ok -eq 0) {{
    Write-Host 'Aucun pilote installe — verifiez le dossier et drivers.json.' -ForegroundColor Red
    exit 1
}}
if ($fail -gt 0) {{
    Write-Host 'Certains pilotes ont echoue ; le deploiement peut continuer (bcdboot, reboot).' -ForegroundColor Yellow
    exit 0
}}
Write-Host 'Pilotes injectes avec succes.' -ForegroundColor Green
exit 0
"""


def generate_startnet_cmd(version: IsoVersion) -> str:
    host = smb_connect_host_for_winpe()
    share = smb_share_name()
    deploy_ps1 = f"{z_scripts_dir(version)}\\{DEPLOY_PS1}"
    unc = f"\\\\{host}\\{share}"

    return f"""@echo off
setlocal EnableDelayedExpansion
REM Generated by iPXE Manager — lance les scripts PowerShell sur le partage boot
wpeinit
echo Preparation disque UEFI (GPT) sur le disque 0...
set "_DP=X:\ipxe-diskpart.txt"
> "%_DP%" (
echo select disk 0
echo clean
echo convert gpt
echo create partition efi size=100
echo format quick fs=fat32 label="System"
echo assign letter=S
echo create partition msr size=16
echo create partition primary
echo format quick fs=ntfs label="Windows"
echo assign letter=W
echo exit
)
diskpart /s "%_DP%"
set "_DPE=%errorlevel%"
del "%_DP%" >nul 2>&1
if not "%_DPE%"=="0" (
  echo diskpart a echoue.
  pause
  goto :eof
)
echo Fin diskpart — reinitialisation reseau...
wpeutil InitializeNetwork >nul 2>&1
wpeutil WaitForNetwork
net start rdr >nul 2>&1
net start mrxsmb20 >nul 2>&1
net start mrxsmb10 >nul 2>&1
net start workstation >nul 2>&1
echo Attente serveur {host} (3 pings OK + pause)...
call :wait_host_ready
net use Z: /delete /y >nul 2>&1
net use \\\\{host}\\IPC$ /user:guest >nul 2>&1
echo Montage du partage boot...
echo Commande : net use Z: {unc} /user:guest
set "_SMB_TRY=0"
:mount_boot_retry
set /a _SMB_TRY+=1
call :wait_host_ready
net use Z: {unc} /user:guest
if not errorlevel 1 goto mount_boot_ok
echo Tentative !_SMB_TRY!/20 echouee (erreur %errorlevel%, 53 = SMB pas pret).
if !_SMB_TRY! lss 20 goto mount_boot_retry
echo Echec montage SMB {unc}
echo Test manuel : net use Z: {unc} /user:guest
pause
goto :eof

REM 3 pings reussis vers le serveur puis pause (~8 s) avant net use
:wait_host_ready
set "_PING_OK=0"
:wait_host_ping_one
ping -n 1 -w 2000 {host} >nul
if errorlevel 1 (
  set "_PING_OK=0"
  call :ipxe_ping_host 3
  goto wait_host_ping_one
)
set /a _PING_OK+=1
if !_PING_OK! lss 3 goto wait_host_ping_one
call :ipxe_ping_host 8
exit /b 0

REM N pings vers le serveur (~1 s entre chaque)
:ipxe_ping_host
ping -n %1 -w 1000 {host} >nul 2>&1
exit /b 0

:mount_boot_ok
echo Partage monte sur Z:
if not exist "{deploy_ps1}" (
  echo Script deploy.ps1 introuvable : {deploy_ps1}
  echo Regenerer les scripts WinPE depuis iPXE Manager.
  pause
  goto :eof
)
echo Lancement du deploiement PowerShell...
powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File "{deploy_ps1}"
if errorlevel 1 (
  echo Le script de deploiement a signale une erreur.
  pause
)
net use Z: /delete /y >nul 2>&1
"""


def write_all_scripts(version: IsoVersion, installs: list[WinpeInstall]) -> Path:
    """Écrit masters.json, deploy.ps1, inject-drivers.ps1 sur le disque."""
    sdir = scripts_dir(version)
    (sdir / MASTERS_JSON).write_text(
        generate_masters_json(version, installs) + "\n",
        encoding="utf-8",
    )
    (sdir / DEPLOY_PS1).write_text(generate_deploy_ps1(version), encoding="utf-8-sig")
    (sdir / INJECT_DRIVERS_PS1).write_text(
        generate_inject_drivers_ps1(version), encoding="utf-8-sig"
    )
    logger.info("Scripts WinPE écrits dans %s (%d master(s))", sdir, len(installs))
    return sdir


def inject_startnet_into_boot_wim(version: IsoVersion) -> Path:
    """Injecte le startnet.cmd minimal dans boot.wim."""
    boot_wim = boot_wim_filesystem_path(version)
    bak = boot_wim.with_suffix(".wim.bak")
    if not bak.is_file():
        import shutil

        shutil.copy2(boot_wim, bak)

    boot_image_index = int(getattr(settings, "winpe_boot_wim_index", 1) or 1)
    content = generate_startnet_cmd(version)

    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".cmd",
        delete=False,
        encoding="utf-8",
        newline="\r\n",
    ) as tf:
        tf.write(content)
        cmd_path = Path(tf.name)

    try:
        src = str(cmd_path.resolve())
        dest_in_wim = "/" + STARTNET_WIM_PATH.replace("\\", "/").lstrip("/")
        proc = run_wimupdate_add(boot_wim, boot_image_index, src, dest_in_wim)
    finally:
        cmd_path.unlink(missing_ok=True)

    if proc.returncode != 0:
        from app.services.iso_extractor import ExtractionError

        tail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-3000:]
        raise ExtractionError(
            f"wimupdate startnet.cmd échoué (code {proc.returncode}) : {tail}"
        )
    return boot_wim


def regenerate_winpe_deployment(
    version: IsoVersion, installs: list[WinpeInstall], *, patch_wim: bool = True
) -> dict:
    """
    Régénère scripts + optionnellement startnet.cmd dans boot.wim.
    """
    if not installs:
        raise ValueError("Ajoutez au moins un master (install.wim) avant de générer les scripts.")
    if patch_wim:
        boot_wim_filesystem_path(version)
    sdir = write_all_scripts(version, installs)
    if patch_wim:
        inject_startnet_into_boot_wim(version)
    return {
        "scripts_dir": str(sdir),
        "masters": len(build_masters_catalog(version, installs)),
        "patched_at": datetime.utcnow().isoformat() + "Z",
    }
