"""
Génère et injecte ``startnet.cmd`` dans ``boot.wim`` (wimlib ``wimupdate``).
"""
from __future__ import annotations

import logging
import shutil
import subprocess
import tempfile
from pathlib import Path

from app.config import settings
from app.models.models import IsoVersion, WinpeInstall
from app.services.iso_extractor import ExtractionError
from app.services.winpe_installs import (
    install_wim_path,
    install_wim_rel_path,
    smb_host_from_settings,
    smb_share_name,
    version_segment,
)

logger = logging.getLogger(__name__)

STARTNET_WIM_PATH = "Windows/System32/startnet.cmd"


def _wimupdate_bin() -> str:
    for name in ("wimupdate", "wimlib-imagex"):
        p = shutil.which(name)
        if p:
            return p
    raise ExtractionError(
        "wimupdate introuvable — installez wimtools sur le serveur : apt install wimtools"
    )


def boot_wim_filesystem_path(version: IsoVersion) -> Path:
    be = version.boot_entry
    if not be or not (be.boot_wim_path or "").strip():
        raise FileNotFoundError(
            "boot.wim absent — extrayez l'ISO WinPE ou uploadez boot.wim avant de choisir une install.wim."
        )
    rel = be.boot_wim_path.replace("\\", "/").lstrip("/")
    path = Path(settings.http_root) / rel
    if not path.is_file():
        raise FileNotFoundError(f"boot.wim introuvable sur le disque : {path}")
    return path


def generate_startnet_cmd(version: IsoVersion, install: WinpeInstall) -> str:
    """
    Script WinPE : wpeinit, montage SMB du partage ``boot``, DISM Apply-Image depuis install.wim.
    """
    host = smb_host_from_settings()
    share = smb_share_name()
    os_slug = version.os_type.slug
    seg = version_segment(version)
    rel = install_wim_rel_path(version, install.slug)
    # Chemin vu après « net use Z: \\host\boot »
    win_rel = rel.replace("/", "\\")
    if win_rel.lower().startswith("boot\\"):
        win_rel = win_rel[5:]
    wim_on_z = f"Z:\\{win_rel}"
    idx = max(1, int(install.wim_index or 1))

    return f"""@echo off
REM Generated by iPXE Manager — {install.label or install.slug}
REM Install: {install.slug} — index DISM {idx}
wpeinit
net use Z: \\\\{host}\\{share} /user:guest ""
if errorlevel 1 (
  echo Echec montage SMB \\\\{host}\\{share}
  pause
  goto :eof
)
set WIM={wim_on_z}
if not exist "%WIM%" (
  echo install.wim introuvable: %WIM%
  echo Verifiez Samba [{share}] et le dossier installs/{install.slug}/
  pause
  goto :eof
)
echo Application de %WIM% vers C:\\ (index {idx}) ...
Dism /Apply-Image /ImageFile:"%WIM%" /Index:{idx} /ApplyDir:C:\\ /CheckIntegrity /Verify
if errorlevel 1 (
  echo DISM /Apply-Image a echoue.
  pause
  goto :eof
)
echo Image appliquee. Redemarrage dans 10 secondes...
wpeutil reboot
"""


def patch_boot_wim_startnet(
    version: IsoVersion,
    install: WinpeInstall,
    *,
    image_index: int | None = None,
) -> Path:
    """
    Sauvegarde boot.wim en .bak si besoin, injecte startnet.cmd via wimupdate.
    Retourne le chemin du boot.wim modifié.
    """
    boot_wim = boot_wim_filesystem_path(version)
    bak = boot_wim.with_suffix(".wim.bak")
    if not bak.is_file():
        shutil.copy2(boot_wim, bak)
        logger.info("Sauvegarde boot.wim → %s", bak)

    idx = image_index if image_index is not None else max(1, int(install.wim_index or 1))
    wim_idx = getattr(settings, "winpe_boot_wim_index", 1) or 1
    # Index dans boot.wim (souvent 1 = Windows PE) ; wim_idx configurable
    boot_image_index = int(wim_idx)

    content = generate_startnet_cmd(version, install)
    wimupdate = _wimupdate_bin()

    if not install_wim_path(version, install.slug).is_file():
        raise FileNotFoundError(
            f"install.wim manquant pour « {install.slug} » — uploadez le fichier d'abord."
        )

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".cmd",
        delete=False,
        encoding="utf-8",
        newline="\r\n",
    ) as tf:
        tf.write(content)
        tf.flush()
        cmd_path = Path(tf.name)

    try:
        # wimlib : « add » + chemin dans la WIM ; repli syntaxe « PATH < file » (anciennes versions)
        attempts = [
            [
                wimupdate,
                str(boot_wim),
                str(boot_image_index),
                "add",
                STARTNET_WIM_PATH,
                str(cmd_path),
            ],
            [
                wimupdate,
                str(boot_wim),
                str(boot_image_index),
                STARTNET_WIM_PATH,
                str(cmd_path),
            ],
        ]
        proc = None
        for cmd in attempts:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=600,
            )
            if proc.returncode == 0:
                break
        if proc is None:
            raise ExtractionError("wimupdate : aucune commande exécutée")
    finally:
        try:
            cmd_path.unlink(missing_ok=True)
        except OSError:
            pass

    if proc.returncode != 0:
        tail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-2000:]
        raise ExtractionError(
            f"wimupdate a échoué (code {proc.returncode}) pour {boot_wim.name} :\n{tail}"
        )

    logger.info(
        "startnet.cmd injecté dans %s (image %s) pour install %s",
        boot_wim,
        boot_image_index,
        install.slug,
    )
    return boot_wim


def activate_winpe_install(version: IsoVersion, install: WinpeInstall) -> None:
    """Point d'entrée : patch boot.wim pour l'install choisie."""
    patch_boot_wim_startnet(version, install)
