"""Fragments PowerShell générés pour WinPE (deploy + pilotes + unattend)."""

from __future__ import annotations


def ps_inject_drivers_lib(
    drivers_json: str,
    drivers_root: str,
    *,
    language_packs_json: str = "",
    language_packs_root: str = "",
) -> str:
    lp_json = language_packs_json or f"{drivers_root}\\..\\language-packs\\language-packs.json"
    lp_root = language_packs_root or f"{drivers_root}\\..\\language-packs"
    return f"""# Generated by iPXE Manager — bibliotheque pilotes + unattend (offline)
param(
    [string]$TargetOS = 'W:\\',
    [string]$DriverProfileKey = ''
)

$ErrorActionPreference = 'Continue'
$script:WinpeInjectCliMode = ($MyInvocation.InvocationName -ne '.')

$script:WinpeDriversJson = '{drivers_json}'
$script:WinpeDriversRoot = '{drivers_root}'
$script:WinpeLanguagePacksJson = '{lp_json}'
$script:WinpeLanguagePacksRoot = '{lp_root}'

function Get-WinpeDriverCatalog {{
    if (-not (Test-Path -LiteralPath $script:WinpeDriversJson)) {{ return $null }}
    $raw = Get-Content -LiteralPath $script:WinpeDriversJson -Raw -ErrorAction SilentlyContinue
    if (-not $raw) {{ return $null }}
    return ($raw | ConvertFrom-Json)
}}

function Get-DriverFolderForKey {{
    param($Catalog, [string]$Key)
    if (-not $Catalog -or -not $Key) {{ return $null }}
    $meta = $Catalog.$Key
    if (-not $meta) {{ return $null }}
    if ($meta.slug) {{ return Join-Path $script:WinpeDriversRoot $meta.slug }}
    $rel = ($meta.path -replace '/', '\\').Trim('\\')
    if ($rel -match '^drivers[\\/](.+)$') {{ return Join-Path $script:WinpeDriversRoot $Matches[1] }}
    return Join-Path $script:WinpeDriversRoot $rel
}}

function Try-DetectDriverProfile {{
    param($Catalog)
    if (-not $Catalog) {{ return $null, $null, 0 }}
    $hint = ''
    try {{
        $cs = Get-CimInstance Win32_ComputerSystem -ErrorAction SilentlyContinue
        if ($cs) {{ $hint = "$($cs.Manufacturer) $($cs.Model)".Trim() }}
    }} catch {{ }}
    if (-not $hint) {{ return $null, $hint, 0 }}
    $bestKey = $null
    $bestScore = 0
    foreach ($prop in $Catalog.PSObject.Properties) {{
        $k = $prop.Name
        $score = 0
        if ($hint -match [regex]::Escape($k)) {{ $score += 10 }}
        $slug = $prop.Value.slug
        if ($slug -and $hint -match [regex]::Escape($slug)) {{ $score += 8 }}
        if ($score -gt $bestScore) {{
            $bestScore = $score
            $bestKey = $k
        }}
    }}
    if ($bestScore -lt 8) {{ return $null, $hint, $bestScore }}
    return $bestKey, $hint, $bestScore
}}

function Install-WinpeDrivers {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$ProfileKey,
        [switch]$Quiet
    )
    if (-not $ProfileKey) {{
        if (-not $Quiet) {{ Write-Host 'Aucun profil pilote.' -ForegroundColor Yellow }}
        return $true
    }}
    $catalog = Get-WinpeDriverCatalog
    if (-not $catalog) {{
        if (-not $Quiet) {{ Write-Host 'drivers.json absent.' -ForegroundColor Yellow }}
        return $true
    }}
    $driverDir = Get-DriverFolderForKey $catalog $ProfileKey
    if (-not $driverDir -or -not (Test-Path -LiteralPath $driverDir)) {{
        Write-Host "Dossier pilotes introuvable : $ProfileKey" -ForegroundColor Red
        return $false
    }}
    $infCount = @(Get-ChildItem -LiteralPath $driverDir -Recurse -Filter '*.inf' -File -ErrorAction SilentlyContinue).Count
    if ($infCount -eq 0) {{
        Write-Host "Aucun .inf dans $driverDir" -ForegroundColor Red
        return $false
    }}
    if (-not $Quiet) {{
        Write-Host "Injection pilotes : $ProfileKey ($infCount .inf)" -ForegroundColor Cyan
    }}
    $imageRoot = $TargetOS.TrimEnd('\\')
    $dismArgs = @('/Image:' + $imageRoot, '/Add-Driver', '/Driver:' + $driverDir, '/Recurse')
    foreach ($scratch in @('X:\', 'S:\', 'T:\')) {{
        if (Test-Path -LiteralPath $scratch) {{
            $dismArgs += '/ScratchDir:' + $scratch.TrimEnd('\\')
            break
        }}
    }}
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{
        Write-Host "DISM Add-Driver echec (code $($p.ExitCode)) — profil $ProfileKey" -ForegroundColor Red
        return $false
    }}
    $added = @(Get-ChildItem -LiteralPath $driverDir -Recurse -Filter '*.inf' -File -ErrorAction SilentlyContinue).Count
    if (-not $Quiet) {{
        Write-Host "DISM Add-Driver OK : $ProfileKey ($added .inf source, pilotes dans le magasin image)." -ForegroundColor Green
    }}
    return $true
}}

function Get-WinpeLanguagePackCatalog {{
    if (-not (Test-Path -LiteralPath $script:WinpeLanguagePacksJson)) {{ return $null }}
    $raw = Get-Content -LiteralPath $script:WinpeLanguagePacksJson -Raw -ErrorAction SilentlyContinue
    if (-not $raw) {{ return $null }}
    return ($raw | ConvertFrom-Json)
}}

function Get-LanguagePackFolderForId {{
    param($Catalog, [string]$LanguageId)
    if (-not $Catalog -or -not $LanguageId) {{ return $null }}
    $meta = $Catalog.$LanguageId
    if (-not $meta) {{ return $null }}
    if ($meta.slug) {{ return Join-Path $script:WinpeLanguagePacksRoot $meta.slug }}
    $rel = ($meta.path -replace '/', '\\').Trim('\\')
    if ($rel -match '^language-packs[\\/](.+)$') {{ return Join-Path $script:WinpeLanguagePacksRoot $Matches[1] }}
    return Join-Path $script:WinpeLanguagePacksRoot $rel
}}

function Get-LanguagePackCabCount {{
    param([string]$Folder)
    if (-not $Folder -or -not (Test-Path -LiteralPath $Folder)) {{ return 0 }}
    return @(Get-ChildItem -LiteralPath $Folder -Filter '*.cab' -File -Recurse -ErrorAction SilentlyContinue).Count
}}

function Install-WinpeLanguagePacks {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$LanguageId,
        [switch]$Quiet
    )
    if (-not $LanguageId) {{
        if (-not $Quiet) {{ Write-Host 'Aucune langue interface selectionnee.' -ForegroundColor Yellow }}
        return $true
    }}
    $catalog = Get-WinpeLanguagePackCatalog
    if (-not $catalog) {{
        if (-not $Quiet) {{ Write-Host 'language-packs.json absent — langue du master conservee.' -ForegroundColor Yellow }}
        return $true
    }}
    $packDir = Get-LanguagePackFolderForId $catalog $LanguageId
    if (-not $packDir -or -not (Test-Path -LiteralPath $packDir)) {{
        if (-not $Quiet) {{ Write-Host "Aucun pack langue sur le serveur pour $LanguageId." -ForegroundColor Yellow }}
        return $true
    }}
    $cabCount = Get-LanguagePackCabCount -Folder $packDir
    if ($cabCount -eq 0) {{
        if (-not $Quiet) {{ Write-Host "Aucun .cab dans $packDir" -ForegroundColor Yellow }}
        return $true
    }}
    if (-not $Quiet) {{
        Write-Host "Injection language pack : $LanguageId ($cabCount .cab, DISM /Add-Package dossier)" -ForegroundColor Cyan
    }}
    $imageRoot = $TargetOS.TrimEnd('\\')
    $dismArgs = @(
        '/Image:' + $imageRoot,
        '/Add-Package',
        '/PackagePath:' + $packDir,
        '/IgnoreCheck'
    )
    foreach ($scratch in @('X:\', 'S:\', 'T:\')) {{
        if (Test-Path -LiteralPath $scratch) {{
            $dismArgs += '/ScratchDir:' + $scratch.TrimEnd('\\')
            break
        }}
    }}
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{
        Write-Host "DISM Add-Package echec pour $LanguageId (code $($p.ExitCode)) — dossier $packDir" -ForegroundColor Red
        return $false
    }}
    if (-not $Quiet) {{
        Write-Host "  OK $LanguageId ($cabCount .cab)" -ForegroundColor Gray
    }}
    return $true
}}

function Get-UnattendNsUri {{
    param([xml]$Doc)
    if ($Doc.DocumentElement -and $Doc.DocumentElement.NamespaceURI) {{
        return $Doc.DocumentElement.NamespaceURI
    }}
    return 'urn:schemas-microsoft-com:unattend'
}}

function Get-UnattendNsMgr {{
    param([xml]$Doc)
    $uri = Get-UnattendNsUri -Doc $Doc
    $mgr = New-Object System.Xml.XmlNamespaceManager($Doc.NameTable)
    $mgr.AddNamespace('u', $uri)
    $mgr.AddNamespace('wcm', 'http://schemas.microsoft.com/WMIConfig/2002/State')
    return $mgr, $uri
}}

function Get-UnattendWcmUri {{
    return 'http://schemas.microsoft.com/WMIConfig/2002/State'
}}

function Ensure-WcmOnUnattendRoot {{
    param([xml]$Doc)
    $root = $Doc.DocumentElement
    if (-not $root) {{ return }}
    $wcmUri = Get-UnattendWcmUri
    if (-not $root.GetAttribute('xmlns:wcm')) {{
        $null = $root.SetAttribute('xmlns:wcm', $wcmUri)
    }}
}}

function Ensure-WcmOnShellComponent {{
    param($Shell)
    $wcmUri = Get-UnattendWcmUri
    if (-not $Shell.GetAttribute('xmlns:wcm')) {{
        $null = $Shell.SetAttribute('xmlns:wcm', $wcmUri)
    }}
}}

function New-UnattendElement {{
    param([xml]$Doc, [string]$LocalName, [string]$NsUri)
    if ($NsUri) {{ return $Doc.CreateElement($LocalName, $NsUri) }}
    return $Doc.CreateElement($LocalName)
}}

function Get-UnattendDirectChild {{
    param($Parent, [string]$LocalName)
    if (-not $Parent) {{ return $null }}
    foreach ($c in @($Parent.ChildNodes)) {{
        if ($c.NodeType -eq [System.Xml.XmlNodeType]::Element -and $c.LocalName -eq $LocalName) {{
            return $c
        }}
    }}
    return $null
}}

function Get-ShellSetupComponentsForPass {{
    param([xml]$Doc, [string]$Pass, $NsMgr)
    $all = @()
    foreach ($settings in @($Doc.SelectNodes("//u:settings[@pass='$Pass']", $NsMgr))) {{
        $all += @($settings.SelectNodes('u:component[@name="Microsoft-Windows-Shell-Setup"]', $NsMgr))
    }}
    return $all
}}

function Merge-UnattendSettingsPasses {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $root = $Doc.DocumentElement
    if (-not $root) {{ return }}
    $primaryByPass = @{{}}
    foreach ($settings in @($root.SelectNodes('u:settings', $NsMgr))) {{
        $pass = $settings.GetAttribute('pass')
        if (-not $pass) {{ continue }}
        if (-not $primaryByPass.ContainsKey($pass)) {{
            $primaryByPass[$pass] = $settings
            continue
        }}
        $primary = $primaryByPass[$pass]
        foreach ($child in @($settings.ChildNodes)) {{
            if ($child.NodeType -ne [System.Xml.XmlNodeType]::Element) {{ continue }}
            $null = $primary.AppendChild($Doc.ImportNode($child, $true))
        }}
        $null = $root.RemoveChild($settings)
    }}
}}

function Merge-InternationalCoreComponents {{
    param([xml]$Doc, $NsMgr, [string]$Pass, [string]$CompName, [string]$NsUri)
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']", $NsMgr)
    if (-not $settings) {{ return }}
    $comps = @($settings.SelectNodes("u:component[@name='$CompName']", $NsMgr))
    if ($comps.Count -le 1) {{ return }}
    Write-Host "Fusion de $($comps.Count) composants $CompName ($Pass)." -ForegroundColor Yellow
    $primary = $comps[0]
    for ($i = 1; $i -lt $comps.Count; $i++) {{
        foreach ($c in @($comps[$i].ChildNodes)) {{
            if ($c.NodeType -ne [System.Xml.XmlNodeType]::Element) {{ continue }}
            Set-UnattendXmlText -Parent $primary -Doc $Doc -NsUri $NsUri -LocalName $c.LocalName -Value $c.InnerText | Out-Null
        }}
        $null = $settings.RemoveChild($comps[$i])
    }}
}}

function Merge-UserAccountsNodes {{
    param($PrimaryUA, $ExtraUA, [xml]$Doc, [string]$NsUri)
    if (-not $PrimaryUA -or -not $ExtraUA) {{ return }}
    $primaryLA = Get-UnattendDirectChild -Parent $PrimaryUA -LocalName 'LocalAccounts'
    $extraLA = Get-UnattendDirectChild -Parent $ExtraUA -LocalName 'LocalAccounts'
    if (-not $extraLA) {{ return }}
    if (-not $primaryLA) {{
        $null = $PrimaryUA.AppendChild($Doc.ImportNode($extraLA, $true))
        return
    }}
    foreach ($acct in @($extraLA.ChildNodes)) {{
        if ($acct.NodeType -ne [System.Xml.XmlNodeType]::Element) {{ continue }}
        if ($acct.LocalName -ne 'LocalAccount') {{ continue }}
        $name = Get-UnattendDirectChild -Parent $acct -LocalName 'Name'
        $exists = $false
        if ($name) {{
            foreach ($pa in @($primaryLA.ChildNodes)) {{
                if ($pa.NodeType -ne [System.Xml.XmlNodeType]::Element) {{ continue }}
                $pn = Get-UnattendDirectChild -Parent $pa -LocalName 'Name'
                if ($pn -and $pn.InnerText -ieq $name.InnerText) {{ $exists = $true; break }}
            }}
        }}
        if (-not $exists) {{
            $null = $primaryLA.AppendChild($Doc.ImportNode($acct, $true))
        }}
    }}
}}

function Merge-OobeShellSetupComponents {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='oobeSystem']", $NsMgr)
    if (-not $settings) {{ return $null }}
    $shells = @($settings.SelectNodes('u:component[@name="Microsoft-Windows-Shell-Setup"]', $NsMgr))
    if ($shells.Count -le 1) {{
        if ($shells.Count -eq 1) {{ Ensure-WcmOnShellComponent -Shell $shells[0] }}
        return $shells[0]
    }}
    Write-Host "Fusion de $($shells.Count) composants Shell-Setup oobeSystem en un seul." -ForegroundColor Yellow
    $primary = $shells[0]
    Ensure-WcmOnShellComponent -Shell $primary
    for ($i = 1; $i -lt $shells.Count; $i++) {{
        $extra = $shells[$i]
        foreach ($localName in @('OOBE', 'UserAccounts', 'AutoLogon')) {{
            $src = Get-UnattendDirectChild -Parent $extra -LocalName $localName
            if (-not $src) {{ continue }}
            $dst = Get-UnattendDirectChild -Parent $primary -LocalName $localName
            if (-not $dst) {{
                $null = $primary.AppendChild($Doc.ImportNode($src, $true))
                continue
            }}
            if ($localName -eq 'OOBE') {{
                foreach ($c in @($src.ChildNodes)) {{
                    if ($c.NodeType -eq [System.Xml.XmlNodeType]::Element) {{
                        Set-UnattendXmlText -Parent $dst -Doc $Doc -NsUri $NsUri -LocalName $c.LocalName -Value $c.InnerText | Out-Null
                    }}
                }}
            }} elseif ($localName -eq 'UserAccounts') {{
                Merge-UserAccountsNodes -PrimaryUA $dst -ExtraUA $src -Doc $Doc -NsUri $NsUri
            }} elseif ($localName -eq 'AutoLogon') {{
                if ($dst) {{ $null = $primary.RemoveChild($dst) }}
                $null = $primary.AppendChild($Doc.ImportNode($src, $true))
            }}
        }}
        $null = $settings.RemoveChild($extra)
    }}
    return $primary
}}

function Repair-UnattendDocumentStructure {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    Ensure-WcmOnUnattendRoot -Doc $Doc
    Merge-UnattendSettingsPasses -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    Merge-InternationalCoreComponents -Doc $Doc -NsMgr $NsMgr -Pass 'windowsPE' -CompName 'Microsoft-Windows-International-Core-WinPE' -NsUri $NsUri
    Merge-InternationalCoreComponents -Doc $Doc -NsMgr $NsMgr -Pass 'oobeSystem' -CompName 'Microsoft-Windows-International-Core' -NsUri $NsUri
    return (Merge-OobeShellSetupComponents -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri)
}}

function Test-UnattendOobeStructureValid {{
    param([xml]$Doc, $NsMgr)
    $shellCount = @($Doc.SelectNodes("//u:settings[@pass='oobeSystem']/u:component[@name='Microsoft-Windows-Shell-Setup']", $NsMgr)).Count
    if ($shellCount -gt 1) {{
        Write-Host "ERREUR structure : $shellCount composants Shell-Setup dans oobeSystem (max 1)." -ForegroundColor Red
        return $false
    }}
    $intlCount = @($Doc.SelectNodes("//u:settings[@pass='oobeSystem']/u:component[@name='Microsoft-Windows-International-Core']", $NsMgr)).Count
    if ($intlCount -gt 1) {{
        Write-Host "ERREUR structure : $intlCount composants International-Core dans oobeSystem (max 1)." -ForegroundColor Red
        return $false
    }}
    return $true
}}

function Ensure-ShellSetupForPass {{
    param([xml]$Doc, [string]$Pass, $NsMgr, [string]$NsUri)
    if ($Pass -eq 'oobeSystem') {{
        Repair-UnattendDocumentStructure -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri | Out-Null
        $merged = Merge-OobeShellSetupComponents -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
        if ($merged) {{ return $merged }}
    }}
    $shells = Get-ShellSetupComponentsForPass -Doc $Doc -Pass $Pass -NsMgr $NsMgr
    if ($shells.Count -gt 0) {{ return $shells[0] }}
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']", $NsMgr)
    if (-not $settings) {{
        $settings = New-UnattendElement -Doc $Doc -LocalName 'settings' -NsUri $NsUri
        $null = $settings.SetAttribute('pass', $Pass)
        $Doc.DocumentElement.AppendChild($settings) | Out-Null
    }}
    $attrs = Get-ShellSetupTemplateAttrs -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    $shell = New-UnattendElement -Doc $Doc -LocalName 'component' -NsUri $NsUri
    $null = $shell.SetAttribute('name', 'Microsoft-Windows-Shell-Setup')
    foreach ($k in $attrs.Keys) {{
        if ($attrs[$k]) {{ $null = $shell.SetAttribute($k, $attrs[$k]) }}
    }}
    Ensure-WcmOnShellComponent -Shell $shell
    $settings.AppendChild($shell) | Out-Null
    return $shell
}}

function Get-ShellSetupTemplateAttrs {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $ref = $Doc.SelectSingleNode('//u:component[@name="Microsoft-Windows-Shell-Setup"]', $NsMgr)
    if ($ref) {{
        return @{{
            processorArchitecture = $ref.GetAttribute('processorArchitecture')
            publicKeyToken = $ref.GetAttribute('publicKeyToken')
            language = $ref.GetAttribute('language')
            versionScope = $ref.GetAttribute('versionScope')
        }}
    }}
    return @{{
        processorArchitecture = 'amd64'
        publicKeyToken = '31bf3856ad364e35'
        language = 'neutral'
        versionScope = 'nonSxS'
    }}
}}

function Set-UnattendXmlText {{
    param($Parent, [xml]$Doc, [string]$NsUri, [string]$LocalName, [string]$Value)
    $node = Get-UnattendDirectChild -Parent $Parent -LocalName $LocalName
    if (-not $node) {{
        $node = New-UnattendElement -Doc $Doc -LocalName $LocalName -NsUri $NsUri
        $null = $Parent.AppendChild($node)
    }}
    $node.InnerText = $Value
    return $node
}}

function Set-UnattendPasswordNode {{
    param($Parent, [xml]$Doc, [string]$NsUri, [string]$Password, [switch]$AsPlainText, [switch]$KeepPlainTextMode)
    $pwEl = Get-UnattendDirectChild -Parent $Parent -LocalName 'Password'
    if (-not $pwEl) {{
        $pwEl = New-UnattendElement -Doc $Doc -LocalName 'Password' -NsUri $NsUri
        $null = $Parent.AppendChild($pwEl)
    }}
    $usePlain = $AsPlainText
    if ($KeepPlainTextMode) {{
        $ptKeep = Get-UnattendDirectChild -Parent $pwEl -LocalName 'PlainText'
        if ($ptKeep -and $ptKeep.InnerText -eq 'true') {{ $usePlain = $true }}
    }}
    if ($usePlain) {{
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsUri $NsUri -LocalName 'Value' -Value $Password | Out-Null
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsUri $NsUri -LocalName 'PlainText' -Value 'true' | Out-Null
    }} else {{
        $blob = ConvertTo-UnattendPasswordBlob -PlainText $Password
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsUri $NsUri -LocalName 'Value' -Value $blob | Out-Null
        Set-UnattendXmlText -Parent $pwEl -Doc $Doc -NsUri $NsUri -LocalName 'PlainText' -Value 'false' | Out-Null
    }}
}}

function Insert-ShellSetupChildBefore {{
    param($Shell, $NewNode, [string]$BeforeLocalName)
    $before = Get-UnattendDirectChild -Parent $Shell -LocalName $BeforeLocalName
    if ($before) {{
        $Shell.InsertBefore($NewNode, $before) | Out-Null
    }} else {{
        $Shell.AppendChild($NewNode) | Out-Null
    }}
}}

function Set-UnattendComputerName {{
    param([xml]$Doc, $NsMgr, [string]$NsUri, [string]$ComputerName)
    $updated = 0
    foreach ($pass in @('specialize', 'generalize')) {{
        $nodes = $Doc.SelectNodes("//u:settings[@pass='$pass']//u:ComputerName", $NsMgr)
        foreach ($n in @($nodes)) {{
            $n.InnerText = $ComputerName
            $updated++
        }}
    }}
    if ($updated -eq 0) {{
        $shell = Ensure-ShellSetupForPass -Doc $Doc -Pass 'specialize' -NsMgr $NsMgr -NsUri $NsUri
        Set-UnattendXmlText -Parent $shell -Doc $Doc -NsUri $NsUri -LocalName 'ComputerName' -Value $ComputerName | Out-Null
        $updated = 1
    }}
    return $updated
}}

function Get-OobeLocalAccountNodes {{
    param([xml]$Doc, $NsMgr)
    return @($Doc.SelectNodes("//u:settings[@pass='oobeSystem']//u:LocalAccount", $NsMgr))
}}

function Find-OobeLocalAccountByName {{
    param([xml]$Doc, $NsMgr, [string]$User)
    foreach ($node in (Get-OobeLocalAccountNodes -Doc $Doc -NsMgr $NsMgr)) {{
        $n = Get-UnattendDirectChild -Parent $node -LocalName 'Name'
        if ($n -and $n.InnerText -ieq $User) {{ return $node }}
    }}
    return $null
}}

function Test-UnattendLocalAccountExistsInDoc {{
    param([xml]$Doc, $NsMgr, [string]$User)
    return [bool](Find-OobeLocalAccountByName -Doc $Doc -NsMgr $NsMgr -User $User)
}}

function Ensure-WcmActionAddOnElement {{
    param($Element)
    if (-not $Element) {{ return }}
    $wcmUri = Get-UnattendWcmUri
    $cur = $Element.GetAttribute('action', $wcmUri)
    if ($cur -ne 'add') {{
        $null = $Element.SetAttribute('action', $wcmUri, 'add')
    }}
    $key = $Element.GetAttribute('keyValue', $wcmUri)
    if (-not $key) {{
        $null = $Element.SetAttribute('keyValue', $wcmUri, [guid]::NewGuid().ToString())
    }}
}}

function Set-LocalAccountFieldsOnNode {{
    param($Acct, [xml]$Doc, [string]$NsUri, [string]$User, [string]$Password)
    Ensure-WcmActionAddOnElement -Element $Acct
    Set-UnattendPasswordNode -Parent $Acct -Doc $Doc -NsUri $NsUri -Password $Password -AsPlainText
    Set-UnattendXmlText -Parent $Acct -Doc $Doc -NsUri $NsUri -LocalName 'Description' -Value ('Compte iPXE Manager — ' + $User) | Out-Null
    Set-UnattendXmlText -Parent $Acct -Doc $Doc -NsUri $NsUri -LocalName 'DisplayName' -Value $User | Out-Null
    Set-UnattendXmlText -Parent $Acct -Doc $Doc -NsUri $NsUri -LocalName 'Group' -Value 'Administrators' | Out-Null
    Set-UnattendXmlText -Parent $Acct -Doc $Doc -NsUri $NsUri -LocalName 'Name' -Value $User | Out-Null
}}

function Test-UnattendLocalAccountConfigured {{
    param([xml]$Doc, $NsMgr, [string]$User)
    $acct = Find-OobeLocalAccountByName -Doc $Doc -NsMgr $NsMgr -User $User
    if (-not $acct) {{ return $false }}
    $wcmUri = Get-UnattendWcmUri
    if ($acct.GetAttribute('action', $wcmUri) -ne 'add') {{ return $false }}
    $name = Get-UnattendDirectChild -Parent $acct -LocalName 'Name'
    $group = Get-UnattendDirectChild -Parent $acct -LocalName 'Group'
    $pw = Get-UnattendDirectChild -Parent $acct -LocalName 'Password'
    $pwVal = $null
    if ($pw) {{ $pwVal = Get-UnattendDirectChild -Parent $pw -LocalName 'Value' }}
    if (-not $name -or -not $group -or -not $pwVal -or -not $pwVal.InnerText) {{ return $false }}
    if ($name.InnerText -ine $User) {{ return $false }}
    if ($group.InnerText -notmatch 'Administrators') {{ return $false }}
    return $true
}}

function Test-UnattendAutoLogonConfigured {{
    param([xml]$Doc, $NsMgr, [string]$User)
    $shells = Get-ShellSetupComponentsForPass -Doc $Doc -Pass 'oobeSystem' -NsMgr $NsMgr
    foreach ($shell in $shells) {{
        $auto = Get-UnattendDirectChild -Parent $shell -LocalName 'AutoLogon'
        if (-not $auto) {{ continue }}
        $en = Get-UnattendDirectChild -Parent $auto -LocalName 'Enabled'
        $un = Get-UnattendDirectChild -Parent $auto -LocalName 'Username'
        if ($en -and $en.InnerText -ieq 'true' -and $un -and $un.InnerText -ieq $User) {{ return $true }}
    }}
    return $false
}}

function Ensure-OobeShellUserAccounts {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $shell = Ensure-ShellSetupForPass -Doc $Doc -Pass 'oobeSystem' -NsMgr $NsMgr -NsUri $NsUri
    Ensure-WcmOnShellComponent -Shell $shell
    Ensure-WcmOnUnattendRoot -Doc $Doc
    $userAccounts = Get-UnattendDirectChild -Parent $shell -LocalName 'UserAccounts'
    if (-not $userAccounts) {{
        $userAccounts = New-UnattendElement -Doc $Doc -LocalName 'UserAccounts' -NsUri $NsUri
        Insert-ShellSetupChildBefore -Shell $shell -NewNode $userAccounts -BeforeLocalName 'AutoLogon'
    }}
    $localAccounts = Get-UnattendDirectChild -Parent $userAccounts -LocalName 'LocalAccounts'
    if (-not $localAccounts) {{
        $localAccounts = New-UnattendElement -Doc $Doc -LocalName 'LocalAccounts' -NsUri $NsUri
        $userAccounts.AppendChild($localAccounts) | Out-Null
    }}
    return $shell, $localAccounts
}}

function Sync-UnattendOobeLocalAccount {{
    param([xml]$Doc, $NsMgr, [string]$NsUri, [string]$User, [string]$Password)
    Ensure-OobeBypassForLocalAccount -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    $shell, $localAccounts = Ensure-OobeShellUserAccounts -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    $existing = Find-OobeLocalAccountByName -Doc $Doc -NsMgr $NsMgr -User $User
    if ($existing) {{
        Set-LocalAccountFieldsOnNode -Acct $existing -Doc $Doc -NsUri $NsUri -User $User -Password $Password
        Write-Host "Compte oobeSystem mis a jour : $User (LocalAccount wcm:action=add)" -ForegroundColor Green
        return 'updated'
    }}
    $acct = New-UnattendElement -Doc $Doc -LocalName 'LocalAccount' -NsUri $NsUri
    Set-LocalAccountFieldsOnNode -Acct $acct -Doc $Doc -NsUri $NsUri -User $User -Password $Password
    $localAccounts.AppendChild($acct) | Out-Null
    Write-Host "Compte oobeSystem ajoute : $User (LocalAccount wcm:action=add)" -ForegroundColor Green
    return 'added'
}}

function Add-UnattendOobeLocalAccount {{
    param([xml]$Doc, $NsMgr, [string]$NsUri, [string]$User, [string]$Password)
    $result = Sync-UnattendOobeLocalAccount -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri -User $User -Password $Password
    if ($result -eq 'added' -or $result -eq 'updated') {{ return $true }}
    return $false
}}

function Update-UnattendAutoLogon {{
    param([xml]$Doc, $Shell, [string]$NsUri, [string]$User, [string]$Password)
    Ensure-WcmOnShellComponent -Shell $Shell
    $auto = Get-UnattendDirectChild -Parent $Shell -LocalName 'AutoLogon'
    if (-not $auto) {{
        $auto = New-UnattendElement -Doc $Doc -LocalName 'AutoLogon' -NsUri $NsUri
        $Shell.AppendChild($auto) | Out-Null
    }}
    Set-UnattendPasswordNode -Parent $auto -Doc $Doc -NsUri $NsUri -Password $Password -AsPlainText
    Set-UnattendXmlText -Parent $auto -Doc $Doc -NsUri $NsUri -LocalName 'Enabled' -Value 'true' | Out-Null
    Set-UnattendXmlText -Parent $auto -Doc $Doc -NsUri $NsUri -LocalName 'LogonCount' -Value '1' | Out-Null
    Set-UnattendXmlText -Parent $auto -Doc $Doc -NsUri $NsUri -LocalName 'Username' -Value $User | Out-Null
    return $true
}}

function Test-UnattendReservedUsername {{
    param([string]$User)
    $reserved = @('Administrator', 'Guest', 'DefaultAccount', 'WDAGUtilityAccount')
    foreach ($r in $reserved) {{
        if ($User -ieq $r) {{ return $true }}
    }}
    return $false
}}

function Ensure-OobeBypassForLocalAccount {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $shell = Ensure-ShellSetupForPass -Doc $Doc -Pass 'oobeSystem' -NsMgr $NsMgr -NsUri $NsUri
    Ensure-WcmOnShellComponent -Shell $shell
    $oobe = Get-UnattendDirectChild -Parent $shell -LocalName 'OOBE'
    if (-not $oobe) {{
        $oobe = New-UnattendElement -Doc $Doc -LocalName 'OOBE' -NsUri $NsUri
        $ua = Get-UnattendDirectChild -Parent $shell -LocalName 'UserAccounts'
        if ($ua) {{
            $shell.InsertBefore($oobe, $ua) | Out-Null
        }} else {{
            Insert-ShellSetupChildBefore -Shell $shell -NewNode $oobe -BeforeLocalName 'AutoLogon'
        }}
    }}
    foreach ($pair in @(
        @('HideEULAPage', 'true'),
        @('HideOEMRegistrationScreen', 'true'),
        @('HideOnlineAccountScreens', 'true'),
        @('HideWirelessSetupInOOBE', 'true'),
        @('HideLocalAccountScreen', 'false'),
        @('NetworkLocation', 'Work'),
        @('ProtectYourPC', '3'),
        @('SkipMachineOOBE', 'true'),
        @('SkipUserOOBE', 'true')
    )) {{
        Set-UnattendXmlText -Parent $oobe -Doc $Doc -NsUri $NsUri -LocalName $pair[0] -Value $pair[1] | Out-Null
    }}
}}

function Save-UnattendDocument {{
    param([xml]$Doc, [string]$Path)
    $Doc.PreserveWhitespace = $false
    $settings = New-Object System.Xml.XmlWriterSettings
    $settings.Encoding = New-Object System.Text.UTF8Encoding $true
    $settings.Indent = $true
    $settings.IndentChars = '  '
    $settings.NewLineChars = "`r`n"
    $settings.OmitXmlDeclaration = $false
    $writer = [System.Xml.XmlWriter]::Create($Path, $settings)
    try {{ $Doc.Save($writer) }} finally {{ $writer.Close() }}
}}

function ConvertTo-UnattendPasswordBlob {{
    param([string]$PlainText)
    if (-not $PlainText) {{ return '' }}
    $bytes = [System.Text.Encoding]::Unicode.GetBytes($PlainText)
    return [Convert]::ToBase64String($bytes)
}}

function Find-OfflineUnattendPath {{
    param([string]$TargetOS = 'W:\\')
    $candidates = @(
        (Join-Path $TargetOS 'Windows\\Panther\\unattend.xml'),
        (Join-Path $TargetOS 'Windows\\System32\\Sysprep\\unattend.xml'),
        (Join-Path $TargetOS 'unattend.xml')
    )
    foreach ($p in $candidates) {{
        if (Test-Path -LiteralPath $p) {{ return $p }}
    }}
    $found = @(Get-ChildItem -LiteralPath $TargetOS -Recurse -Filter 'unattend.xml' -File -ErrorAction SilentlyContinue | Select-Object -First 1)
    if ($found) {{ return $found.FullName }}
    return $null
}}

function New-MinimalUnattendDocument {{
    $doc = New-Object System.Xml.XmlDocument
    $doc.PreserveWhitespace = $true
    $nsUri = 'urn:schemas-microsoft-com:unattend'
    $wcmUri = Get-UnattendWcmUri
    $decl = $doc.CreateXmlDeclaration('1.0', 'utf-8', $null)
    $doc.AppendChild($decl) | Out-Null
    $root = $doc.CreateElement('unattend', $nsUri)
    $null = $root.SetAttribute('xmlns:wcm', $wcmUri)
    $doc.AppendChild($root) | Out-Null
    return $doc
}}

function Get-OrCreateOfflineUnattendDocument {{
    param([string]$TargetOS = 'W:\\')
    $pantherDir = Join-Path $TargetOS 'Windows\\Panther'
    $pantherPath = Join-Path $pantherDir 'unattend.xml'
    if (-not (Test-Path -LiteralPath $pantherDir)) {{
        New-Item -ItemType Directory -Path $pantherDir -Force | Out-Null
    }}
    if (Test-Path -LiteralPath $pantherPath) {{
        $doc = New-Object System.Xml.XmlDocument
        $doc.PreserveWhitespace = $true
        $doc.Load($pantherPath)
        Ensure-WcmOnUnattendRoot -Doc $doc
        return $doc, $pantherPath
    }}
    $sourcePath = Find-OfflineUnattendPath -TargetOS $TargetOS
    if ($sourcePath -and ($sourcePath -ne $pantherPath)) {{
        Write-Host "Unattend source : $sourcePath (fusion vers Panther)" -ForegroundColor Cyan
        $doc = New-Object System.Xml.XmlDocument
        $doc.PreserveWhitespace = $true
        $doc.Load($sourcePath)
        Ensure-WcmOnUnattendRoot -Doc $doc
        return $doc, $pantherPath
    }}
    Write-Host 'Creation unattend.xml minimal dans Panther (master sans answer file).' -ForegroundColor Yellow
    return (New-MinimalUnattendDocument), $pantherPath
}}

function Get-UiLanguageById {{
    param([string]$LanguageId)
    if (-not $LanguageId) {{ return $null }}
    foreach ($p in @($script:WinpeUiLanguages)) {{
        if ($p.id -eq $LanguageId) {{ return $p }}
    }}
    return $null
}}

function Get-KeyboardById {{
    param([string]$KeyboardId)
    if (-not $KeyboardId) {{ return $null }}
    foreach ($p in @($script:WinpeKeyboardLayouts)) {{
        if ($p.id -eq $KeyboardId) {{ return $p }}
    }}
    return $null
}}

function Get-RegionById {{
    param([string]$RegionId)
    if (-not $RegionId) {{ return $null }}
    foreach ($p in @($script:WinpeRegions)) {{
        if ($p.id -eq $RegionId) {{ return $p }}
    }}
    return $null
}}

function Get-InternationalComponentName {{
    param([bool]$WinPE)
    if ($WinPE) {{ return 'Microsoft-Windows-International-Core-WinPE' }}
    return 'Microsoft-Windows-International-Core'
}}

function Ensure-InternationalComponentForPass {{
    param([xml]$Doc, [string]$Pass, $NsMgr, [string]$NsUri, [bool]$WinPE)
    $compName = Get-InternationalComponentName -WinPE $WinPE
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']", $NsMgr)
    if (-not $settings) {{
        $settings = New-UnattendElement -Doc $Doc -LocalName 'settings' -NsUri $NsUri
        $null = $settings.SetAttribute('pass', $Pass)
        $Doc.DocumentElement.AppendChild($settings) | Out-Null
    }}
    $comp = $settings.SelectSingleNode("u:component[@name='$compName']", $NsMgr)
    if ($comp) {{ return $comp }}
    $attrs = Get-ShellSetupTemplateAttrs -Doc $Doc -NsMgr $NsMgr -NsUri $NsUri
    $comp = New-UnattendElement -Doc $Doc -LocalName 'component' -NsUri $NsUri
    $null = $comp.SetAttribute('name', $compName)
    foreach ($k in $attrs.Keys) {{
        if ($attrs[$k]) {{ $null = $comp.SetAttribute($k, $attrs[$k]) }}
    }}
    $settings.AppendChild($comp) | Out-Null
    return $comp
}}

function Set-InternationalFieldsOnComponent {{
    param($Comp, [xml]$Doc, [string]$NsUri, $UiLang, $Region, [string]$InputLocale, [bool]$IncludeSetupUiLanguage)
    if ($IncludeSetupUiLanguage) {{
        $sul = Get-UnattendDirectChild -Parent $Comp -LocalName 'SetupUILanguage'
        if (-not $sul) {{
            $sul = New-UnattendElement -Doc $Doc -LocalName 'SetupUILanguage' -NsUri $NsUri
            if ($Comp.FirstChild) {{
                $Comp.InsertBefore($sul, $Comp.FirstChild) | Out-Null
            }} else {{
                $Comp.AppendChild($sul) | Out-Null
            }}
        }}
        Set-UnattendXmlText -Parent $sul -Doc $Doc -NsUri $NsUri -LocalName 'UILanguage' -Value $UiLang.setup_ui_language | Out-Null
    }}
    Set-UnattendXmlText -Parent $Comp -Doc $Doc -NsUri $NsUri -LocalName 'InputLocale' -Value $InputLocale | Out-Null
    Set-UnattendXmlText -Parent $Comp -Doc $Doc -NsUri $NsUri -LocalName 'SystemLocale' -Value $Region.system_locale | Out-Null
    Set-UnattendXmlText -Parent $Comp -Doc $Doc -NsUri $NsUri -LocalName 'UILanguage' -Value $UiLang.ui_language | Out-Null
    Set-UnattendXmlText -Parent $Comp -Doc $Doc -NsUri $NsUri -LocalName 'UILanguageFallback' -Value $UiLang.ui_language_fallback | Out-Null
    Set-UnattendXmlText -Parent $Comp -Doc $Doc -NsUri $NsUri -LocalName 'UserLocale' -Value $Region.user_locale | Out-Null
}}

function Set-UnattendLocaleSettings {{
    param([xml]$Doc, $NsMgr, [string]$NsUri, $UiLang, $Region, [string]$InputLocale)
    if (-not $UiLang -or -not $Region -or -not $InputLocale) {{ return }}
    $pe = Ensure-InternationalComponentForPass -Doc $Doc -Pass 'windowsPE' -NsMgr $NsMgr -NsUri $NsUri -WinPE $true
    Set-InternationalFieldsOnComponent -Comp $pe -Doc $Doc -NsUri $NsUri -UiLang $UiLang -Region $Region -InputLocale $InputLocale -IncludeSetupUiLanguage $true
    $spec = Ensure-InternationalComponentForPass -Doc $Doc -Pass 'specialize' -NsMgr $NsMgr -NsUri $NsUri -WinPE $false
    Set-InternationalFieldsOnComponent -Comp $spec -Doc $Doc -NsUri $NsUri -UiLang $UiLang -Region $Region -InputLocale $InputLocale -IncludeSetupUiLanguage $false
    $oob = Ensure-InternationalComponentForPass -Doc $Doc -Pass 'oobeSystem' -NsMgr $NsMgr -NsUri $NsUri -WinPE $false
    Set-InternationalFieldsOnComponent -Comp $oob -Doc $Doc -NsUri $NsUri -UiLang $UiLang -Region $Region -InputLocale $InputLocale -IncludeSetupUiLanguage $false
}}

function Get-UnattendIntlFieldValue {{
    param([xml]$Doc, $NsMgr, [string]$Pass, [string]$LocalName)
    $node = $Doc.SelectSingleNode("//u:settings[@pass='$Pass']/u:component[contains(@name,'International-Core')]//u:$LocalName", $NsMgr)
    if ($node) {{ return $node.InnerText }}
    return ''
}}

function Ensure-PnpSysprepForSpecialize {{
    param([xml]$Doc, $NsMgr, [string]$NsUri)
    $settings = $Doc.SelectSingleNode("//u:settings[@pass='specialize']", $NsMgr)
    if (-not $settings) {{
        $settings = New-UnattendElement -Doc $Doc -LocalName 'settings' -NsUri $NsUri
        $null = $settings.SetAttribute('pass', 'specialize')
        $Doc.DocumentElement.AppendChild($settings) | Out-Null
    }}
    $comp = $settings.SelectSingleNode("u:component[@name='Microsoft-Windows-Pnp-Sysprep']", $NsMgr)
    if (-not $comp) {{
        $comp = New-UnattendElement -Doc $Doc -LocalName 'component' -NsUri $NsUri
        $null = $comp.SetAttribute('name', 'Microsoft-Windows-Pnp-Sysprep')
        $null = $comp.SetAttribute('processorArchitecture', 'amd64')
        $null = $comp.SetAttribute('publicKeyToken', '31bf3856ad364e35')
        $null = $comp.SetAttribute('language', 'neutral')
        $null = $comp.SetAttribute('versionScope', 'nonSxS')
        $settings.AppendChild($comp) | Out-Null
    }}
    Set-UnattendXmlText -Parent $comp -Doc $Doc -NsUri $NsUri -LocalName 'PersistAllDeviceInstalls' -Value 'true' | Out-Null
    Set-UnattendXmlText -Parent $comp -Doc $Doc -NsUri $NsUri -LocalName 'DoNotCleanUpNonPresentDevices' -Value 'true' | Out-Null
}}

function Get-OfflineImageDefaultUiLanguage {{
    param([string]$TargetOS = 'W:\\')
    $imageRoot = $TargetOS.TrimEnd('\\')
    if (-not (Test-Path -LiteralPath (Join-Path $imageRoot 'Windows'))) {{ return '' }}
    $tmp = [System.IO.Path]::GetTempFileName()
    try {{
        $p = Start-Process -FilePath 'dism.exe' -ArgumentList @('/Image:' + $imageRoot, '/Get-Intl', '/English') -Wait -PassThru -NoNewWindow -RedirectStandardOutput $tmp
        if ($p.ExitCode -ne 0) {{ return '' }}
        $lines = Get-Content -LiteralPath $tmp -ErrorAction SilentlyContinue
        foreach ($line in @($lines)) {{
            if ($line -match 'Default UI Language\s*:\s*(\S+)') {{ return $Matches[1].Trim() }}
        }}
    }} finally {{
        Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue
    }}
    return ''
}}

function Set-OfflineImageIntlDefaults {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$LanguageId,
        [string]$InputLocale = ''
    )
    if (-not $LanguageId) {{ return $true }}
    $imageRoot = $TargetOS.TrimEnd('\\')
    Write-Host "DISM Set-SKUIntlDefaults:$LanguageId (langue par defaut dans l image)..." -ForegroundColor Cyan
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList @('/Image:' + $imageRoot, '/Set-SKUIntlDefaults:' + $LanguageId, '/Quiet') -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{
        Write-Host "ERREUR Set-SKUIntlDefaults:$LanguageId (code $($p.ExitCode))." -ForegroundColor Red
        Write-Host 'Verifiez Client-Language-Pack + build identique au master.' -ForegroundColor Red
        return $false
    }}
    Write-Host "Set-SKUIntlDefaults:$LanguageId OK." -ForegroundColor Green
    if ($InputLocale -and $InputLocale.Trim()) {{
        $il = $InputLocale.Trim()
        Write-Host "DISM Set-InputLocale:$il..." -ForegroundColor Cyan
        $p2 = Start-Process -FilePath 'dism.exe' -ArgumentList @('/Image:' + $imageRoot, '/Set-InputLocale:' + $il, '/Quiet') -Wait -PassThru -NoNewWindow
        if ($p2.ExitCode -ne 0) {{
            Write-Host "Avertissement Set-InputLocale (code $($p2.ExitCode)) — clavier via unattend au boot." -ForegroundColor Yellow
        }}
    }}
    $detected = Get-OfflineImageDefaultUiLanguage -TargetOS $TargetOS
    if ($detected -and ($detected -ine $LanguageId)) {{
        Write-Host "ERREUR verification Get-Intl : attendu $LanguageId, image=$detected" -ForegroundColor Red
        return $false
    }}
    if ($detected) {{
        Write-Host "Verification Get-Intl : Default UI Language = $detected" -ForegroundColor Green
    }}
    return $true
}}

function Apply-OfflineUnattendIntlToImage {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$UnattendPath,
        [string]$LanguageId,
        [string]$InputLocale = ''
    )
    if (-not (Test-Path -LiteralPath (Join-Path ($TargetOS.TrimEnd('\\')) 'Windows'))) {{ return $false }}
    if (-not $LanguageId) {{ return $true }}
    $imageRoot = $TargetOS.TrimEnd('\\')
    if ($UnattendPath -and (Test-Path -LiteralPath $UnattendPath)) {{
        Write-Host 'Fusion unattend dans l image (DISM Apply-Unattend)...' -ForegroundColor Cyan
        $args = @('/Image:' + $imageRoot, '/Apply-Unattend:' + $UnattendPath, '/Quiet')
        $p = Start-Process -FilePath 'dism.exe' -ArgumentList $args -Wait -PassThru -NoNewWindow
        if ($p.ExitCode -eq 0) {{
            Write-Host 'DISM Apply-Unattend OK.' -ForegroundColor Green
        }} else {{
            Write-Host "DISM Apply-Unattend code $($p.ExitCode) — poursuite via Set-SKUIntlDefaults." -ForegroundColor Yellow
        }}
    }}
    return (Set-OfflineImageIntlDefaults -TargetOS $TargetOS -LanguageId $LanguageId -InputLocale $InputLocale)
}}

function Update-OfflineUnattend {{
    param(
        [string]$TargetOS = 'W:\\',
        [string]$ComputerName = '',
        [string]$LocalUser = '',
        [string]$LocalPassword = '',
        [string]$LanguageId = '',
        [string]$RegionId = '',
        [string]$KeyboardId = '',
        [string]$LocaleId = ''
    )
    $doc, $path = Get-OrCreateOfflineUnattendDocument -TargetOS $TargetOS
    Write-Host "Personnalisation : $path" -ForegroundColor Cyan
    $nsMgr, $nsUri = Get-UnattendNsMgr -Doc $doc
    Repair-UnattendDocumentStructure -Doc $doc -NsMgr $nsMgr -NsUri $nsUri | Out-Null
    $changed = $false
    $userRequested = ($LocalUser -and $LocalUser.Trim())
    $userReady = $false

    $legacy = if ($LocaleId -and $LocaleId.Trim()) {{ $LocaleId.Trim() }} else {{ '' }}
    $langId = if ($LanguageId -and $LanguageId.Trim()) {{ $LanguageId.Trim() }} elseif ($legacy) {{ $legacy }} else {{ $script:WinpeDefaultUiLanguageId }}
    $regionId = if ($RegionId -and $RegionId.Trim()) {{ $RegionId.Trim() }} elseif ($legacy) {{ $legacy }} else {{ $script:WinpeDefaultRegionId }}
    $kbId = if ($KeyboardId -and $KeyboardId.Trim()) {{ $KeyboardId.Trim() }} elseif ($legacy) {{ $legacy }} else {{ $script:WinpeDefaultKeyboardId }}
    $uiLang = Get-UiLanguageById -LanguageId $langId
    $region = Get-RegionById -RegionId $regionId
    $keyboard = Get-KeyboardById -KeyboardId $kbId
    if ($uiLang -and $region -and $keyboard) {{
        Set-UnattendLocaleSettings -Doc $doc -NsMgr $nsMgr -NsUri $nsUri -UiLang $uiLang -Region $region -InputLocale $keyboard.input_locale
        Ensure-PnpSysprepForSpecialize -Doc $doc -NsMgr $nsMgr -NsUri $nsUri
        Write-Host "Langue interface : $($uiLang.label) ($($uiLang.id))" -ForegroundColor Green
        Write-Host "Region (formats) : $($region.label) ($($region.id))" -ForegroundColor Green
        Write-Host "Clavier : $($keyboard.label) ($($keyboard.input_locale))" -ForegroundColor Green
        $changed = $true
    }} else {{
        if (-not $uiLang) {{ Write-Host "Langue interface inconnue : $langId — non modifiee." -ForegroundColor Yellow }}
        if (-not $region) {{ Write-Host "Region inconnue : $regionId — non modifiee." -ForegroundColor Yellow }}
        if (-not $keyboard) {{ Write-Host "Clavier inconnu : $kbId — non modifie." -ForegroundColor Yellow }}
    }}

    if ($ComputerName -and $ComputerName.Trim()) {{
        $cn = $ComputerName.Trim()
        if ($cn.Length -gt 15) {{ $cn = $cn.Substring(0, 15) }}
        $cn = $cn -replace '[^a-zA-Z0-9\\-]', ''
        if ($cn) {{
            $n = Set-UnattendComputerName -Doc $doc -NsMgr $nsMgr -NsUri $nsUri -ComputerName $cn
            Write-Host "Nom machine : $cn" -ForegroundColor Green
            $changed = $true
        }}
    }}

    if ($userRequested) {{
        $user = $LocalUser.Trim() -replace '[^a-zA-Z0-9._-]', ''
        if (-not $user) {{
            Write-Host 'Nom utilisateur invalide — compte local ignore.' -ForegroundColor Red
        }} elseif (Test-UnattendReservedUsername -User $user) {{
            Write-Host "Nom reserve Windows ($user) — choisissez un autre utilisateur." -ForegroundColor Red
        }} elseif (-not $LocalPassword) {{
            Write-Host 'Mot de passe requis pour un compte local — compte ignore.' -ForegroundColor Red
        }} else {{
            $wrongPass = @($doc.SelectNodes("//u:settings[@pass!='oobeSystem']//u:LocalAccount", $nsMgr))
            if ($wrongPass.Count -gt 0) {{
                Write-Host "ATTENTION : $($wrongPass.Count) LocalAccount hors pass oobeSystem (ignores par Setup)." -ForegroundColor Yellow
            }}
            $syncResult = Sync-UnattendOobeLocalAccount -Doc $doc -NsMgr $nsMgr -NsUri $nsUri -User $user -Password $LocalPassword
            if ($syncResult -eq 'added' -or $syncResult -eq 'updated') {{
                $shellOobe = (Ensure-OobeShellUserAccounts -Doc $doc -NsMgr $nsMgr -NsUri $nsUri)[0]
                Update-UnattendAutoLogon -Doc $doc -Shell $shellOobe -NsUri $nsUri -User $user -Password $LocalPassword | Out-Null
                if (Test-UnattendLocalAccountConfigured -Doc $doc -NsMgr $nsMgr -User $user) {{
                    Write-Host "Validation OK : oobeSystem/UserAccounts/LocalAccount/$user" -ForegroundColor Green
                    if (Test-UnattendAutoLogonConfigured -Doc $doc -NsMgr $nsMgr -User $user) {{
                        Write-Host "Validation OK : oobeSystem/AutoLogon/$user" -ForegroundColor Green
                    }} else {{
                        Write-Host 'ATTENTION : AutoLogon oobeSystem incomplet.' -ForegroundColor Yellow
                    }}
                    $userReady = $true
                    $changed = $true
                }} else {{
                    Write-Host 'ERREUR : LocalAccount oobeSystem invalide apres sync (wcm:action, Name, Group, Password).' -ForegroundColor Red
                }}
            }} else {{
                Write-Host "Impossible de synchroniser le compte $user dans oobeSystem." -ForegroundColor Red
            }}
        }}
    }}

    if ($changed) {{
        Repair-UnattendDocumentStructure -Doc $doc -NsMgr $nsMgr -NsUri $nsUri | Out-Null
        if (-not (Test-UnattendOobeStructureValid -Doc $doc -NsMgr $nsMgr)) {{
            Write-Host 'ERREUR : structure oobeSystem invalide (composants dupliques).' -ForegroundColor Red
            return $false
        }}
        Save-UnattendDocument -Doc $doc -Path $path
        Write-Host "Unattend enregistre : $path" -ForegroundColor Green
        $uiWritten = Get-UnattendIntlFieldValue -Doc $doc -NsMgr $nsMgr -Pass 'oobeSystem' -LocalName 'UILanguage'
        if ($uiWritten) {{
            Write-Host "Verification XML oobeSystem/UILanguage = $uiWritten" -ForegroundColor Cyan
        }}
        if ($uiLang) {{
            $intlOk = Apply-OfflineUnattendIntlToImage -TargetOS $TargetOS -UnattendPath $path -LanguageId $uiLang.id -InputLocale $keyboard.input_locale
            if (-not $intlOk) {{
                Write-Host 'ERREUR : langue non gravee dans l image offline (Set-SKUIntlDefaults / Get-Intl).' -ForegroundColor Red
                return $false
            }}
        }}
    }} elseif (-not $userRequested) {{
        Write-Host 'Aucune modification unattend (valeurs par defaut du master).' -ForegroundColor Gray
    }}
    if ($userRequested -and -not $userReady) {{
        Write-Host 'ERREUR : compte local demande mais non injecte dans unattend.xml.' -ForegroundColor Red
        return $false
    }}
    return $true
}}

if ($script:WinpeInjectCliMode) {{
    if ($DriverProfileKey) {{
        $ok = Install-WinpeDrivers -TargetOS $TargetOS -ProfileKey $DriverProfileKey
        if (-not $ok) {{ exit 1 }}
    }}
    exit 0
}}
"""


def ps_deploy_wizard(scripts_root: str, masters_file: str) -> str:
    from app.services.winpe_locale_presets import (
        default_keyboard_id,
        default_region_id,
        default_ui_language_id,
        keyboards_for_ps_embed,
        regions_for_ps_embed,
        ui_languages_for_ps_embed,
    )

    ui_json = ui_languages_for_ps_embed()
    region_json = regions_for_ps_embed()
    kb_json = keyboards_for_ps_embed()
    default_ui = default_ui_language_id()
    default_region = default_region_id()
    default_kb = default_keyboard_id()

    return f"""# Generated by iPXE Manager — assistant de deploiement WinPE
$ErrorActionPreference = 'Stop'
$ScriptsRoot = '{scripts_root}'
$MastersFile = Join-Path $ScriptsRoot '{masters_file}'
$TargetOS    = 'W:\\'
$TargetWin   = 'W:\\Windows'
$script:WinpeDefaultUiLanguageId = '{default_ui}'
$script:WinpeDefaultRegionId = '{default_region}'
$script:WinpeDefaultKeyboardId = '{default_kb}'

$script:WinpeUiLanguages = @'
{ui_json}
'@ | ConvertFrom-Json

$script:WinpeRegions = @'
{region_json}
'@ | ConvertFrom-Json

$script:WinpeKeyboardLayouts = @'
{kb_json}
'@ | ConvertFrom-Json

$injectLib = Join-Path $ScriptsRoot 'inject-drivers.ps1'
if (-not (Test-Path -LiteralPath $injectLib)) {{
    Write-Host "Bibliotheque introuvable : $injectLib" -ForegroundColor Red
    Pause; exit 1
}}
. $injectLib

function Test-WinpeGuiAvailable {{
    try {{
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
        Add-Type -AssemblyName System.Drawing -ErrorAction Stop
        return $true
    }} catch {{ return $false }}
}}

function Read-ConsoleMenuChoice {{
    param($Items, [string]$Prompt, [string]$DefaultId)
    $ids = @($Items | ForEach-Object {{ $_.id }})
    $defIdx = [array]::IndexOf($ids, $DefaultId)
    if ($defIdx -lt 0) {{ $defIdx = 0 }}
    for ($k = 0; $k -lt $Items.Count; $k++) {{
        Write-Host "[$($k+1)] $($Items[$k].label)"
    }}
    $idx = 0
    while ($true) {{
        $lc = Read-Host "$Prompt [$($defIdx+1)]"
        if ([string]::IsNullOrWhiteSpace($lc)) {{ $idx = $defIdx; break }}
        if ([int]::TryParse($lc, [ref]$idx) -and $idx -ge 1 -and $idx -le $Items.Count) {{ $idx--; break }}
        Write-Host 'Choix invalide.' -ForegroundColor Red
    }}
    return $Items[$idx]
}}

function Show-ConsoleDeployWizard {{
    param($Masters, $Catalog, $AutoDriverKey, $DriverHint)
    Clear-Host
    Write-Host '=== iPXE Manager — Deploiement (console) ===' -ForegroundColor Cyan
    for ($i = 0; $i -lt $Masters.Count; $i++) {{
        Write-Host "[$($i+1)] $($Masters[$i].label) ($($Masters[$i].slug))"
    }}
    $mIdx = 0
    while ($true) {{
        $c = Read-Host 'Master'
        if ([int]::TryParse($c, [ref]$mIdx) -and $mIdx -ge 1 -and $mIdx -le $Masters.Count) {{ break }}
        Write-Host 'Choix invalide.' -ForegroundColor Red
    }}
    $master = $Masters[$mIdx - 1]
    $driverKey = $AutoDriverKey
    if (-not $driverKey -and $Catalog) {{
        Write-Host "Machine non reconnue ($DriverHint). Choisissez un profil pilotes." -ForegroundColor Yellow
        $keys = @($Catalog.PSObject.Properties.Name | Sort-Object)
        for ($j = 0; $j -lt $keys.Count; $j++) {{ Write-Host "[$($j+1)] $($keys[$j])" }}
        Write-Host '[0] Aucun pilote'
        $dIdx = -1
        while ($true) {{
            $dc = Read-Host 'Profil pilotes'
            if ($dc -eq '0') {{ $driverKey = $null; break }}
            if ([int]::TryParse($dc, [ref]$dIdx) -and $dIdx -ge 1 -and $dIdx -le $keys.Count) {{
                $driverKey = $keys[$dIdx - 1]; break
            }}
        }}
    }}
    Write-Host ''
    Write-Host 'Langue interface Windows (setup + OOBE) :' -ForegroundColor Cyan
    $uiPick = Read-ConsoleMenuChoice -Items $script:WinpeUiLanguages -Prompt 'Langue interface' -DefaultId $script:WinpeDefaultUiLanguageId
    Write-Host ''
    Write-Host 'Region / formats (dates, nombres, devise) :' -ForegroundColor Cyan
    $regionPick = Read-ConsoleMenuChoice -Items $script:WinpeRegions -Prompt 'Region' -DefaultId $script:WinpeDefaultRegionId
    Write-Host ''
    Write-Host 'Disposition clavier :' -ForegroundColor Cyan
    $kbPick = Read-ConsoleMenuChoice -Items $script:WinpeKeyboardLayouts -Prompt 'Clavier' -DefaultId $script:WinpeDefaultKeyboardId
    $cn = Read-Host 'Nom machine (Entree = defaut master)'
    $addUser = Read-Host 'Ajouter un utilisateur local ? (O/N)'
    $lu = ''; $lp = ''
    if ($addUser -match '^[oOyY]') {{
        $lu = Read-Host 'Nom utilisateur'
        while (-not $lp) {{
            $lp = Read-Host 'Mot de passe (obligatoire)'
            if (-not $lp) {{ Write-Host 'Mot de passe requis.' -ForegroundColor Red }}
        }}
    }}
    return [pscustomobject]@{{
        Master = $master
        DriverProfileKey = $driverKey
        LanguageId = $uiPick.id
        RegionId = $regionPick.id
        KeyboardId = $kbPick.id
        ComputerName = $cn
        LocalUser = $lu
        LocalPassword = $lp
    }}
}}

function Show-WinpeDeployWizard {{
    param($Masters, $Catalog, $AutoDriverKey, $DriverHint, $RequireManualDriver)
    if (-not (Test-WinpeGuiAvailable)) {{
        return Show-ConsoleDeployWizard -Masters $Masters -Catalog $Catalog -AutoDriverKey $AutoDriverKey -DriverHint $DriverHint
    }}
    Add-Type -AssemblyName System.Windows.Forms
    Add-Type -AssemblyName System.Drawing

    $form = New-Object System.Windows.Forms.Form
    $form.Text = 'iPXE Manager — Deploiement'
    $form.Size = New-Object System.Drawing.Size(520, 754)
    $form.StartPosition = 'CenterScreen'
    $form.FormBorderStyle = 'FixedDialog'
    $form.MaximizeBox = $false

    $lblM = New-Object System.Windows.Forms.Label
    $lblM.Text = 'Master (image Windows)'
    $lblM.Location = New-Object System.Drawing.Point(12, 12)
    $lblM.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblM)

    $lstM = New-Object System.Windows.Forms.ListBox
    $lstM.Location = New-Object System.Drawing.Point(12, 34)
    $lstM.Size = New-Object System.Drawing.Size(480, 100)
    # Force un affichage vertical item-par-item (pas de colonnes "stackees").
    $lstM.MultiColumn = $false
    $lstM.IntegralHeight = $false
    $lstM.SelectionMode = [System.Windows.Forms.SelectionMode]::One
    $lstM.ColumnWidth = 480
    $lstM.HorizontalScrollbar = $true
    foreach ($m in $Masters) {{
        $disp = if ($m.label -and $m.label -ne $m.slug) {{ "$($m.slug) — $($m.label)" }} else {{ "$($m.slug)" }}
        [void]$lstM.Items.Add($disp)
    }}
    if ($lstM.Items.Count -gt 0) {{ $lstM.SelectedIndex = 0 }}
    $form.Controls.Add($lstM)

    $lblD = New-Object System.Windows.Forms.Label
    if ($RequireManualDriver) {{
        $lblD.Text = 'La machine n''a pas ete reconnue. Veuillez choisir les pilotes souhaites.'
        $lblD.ForeColor = [System.Drawing.Color]::DarkOrange
    }} elseif ($AutoDriverKey) {{
        $lblD.Text = "Pilotes : profil « $AutoDriverKey » detecte automatiquement."
        $lblD.ForeColor = [System.Drawing.Color]::DarkGreen
    }} else {{
        $lblD.Text = 'Pilotes (optionnel)'
    }}
    $lblD.Location = New-Object System.Drawing.Point(12, 142)
    $lblD.Size = New-Object System.Drawing.Size(480, 36)
    $form.Controls.Add($lblD)

    $cmbD = New-Object System.Windows.Forms.ComboBox
    $cmbD.Location = New-Object System.Drawing.Point(12, 180)
    $cmbD.Size = New-Object System.Drawing.Size(480, 24)
    $cmbD.DropDownStyle = 'DropDownList'
    [void]$cmbD.Items.Add('(aucun pilote)')
    if ($Catalog) {{
        foreach ($k in ($Catalog.PSObject.Properties.Name | Sort-Object)) {{ [void]$cmbD.Items.Add($k) }}
    }}
    if ($AutoDriverKey -and $cmbD.Items.Contains($AutoDriverKey)) {{
        $cmbD.SelectedItem = $AutoDriverKey
    }} else {{
        $cmbD.SelectedIndex = 0
    }}
    $form.Controls.Add($cmbD)

    $lblLang = New-Object System.Windows.Forms.Label
    $lblLang.Text = 'Langue interface (setup + OOBE)'
    $lblLang.Location = New-Object System.Drawing.Point(12, 218)
    $lblLang.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblLang)

    $cmbLang = New-Object System.Windows.Forms.ComboBox
    $cmbLang.Location = New-Object System.Drawing.Point(12, 240)
    $cmbLang.Size = New-Object System.Drawing.Size(480, 24)
    $cmbLang.DropDownStyle = 'DropDownList'
    foreach ($lp in @($script:WinpeUiLanguages)) {{
        [void]$cmbLang.Items.Add($lp.label)
    }}
    $defLangIdx = 0
    for ($li = 0; $li -lt $script:WinpeUiLanguages.Count; $li++) {{
        if ($script:WinpeUiLanguages[$li].id -eq $script:WinpeDefaultUiLanguageId) {{
            $defLangIdx = $li
            break
        }}
    }}
    $cmbLang.SelectedIndex = $defLangIdx
    $form.Controls.Add($cmbLang)

    $lblReg = New-Object System.Windows.Forms.Label
    $lblReg.Text = 'Region / formats (dates, nombres, devise)'
    $lblReg.Location = New-Object System.Drawing.Point(12, 272)
    $lblReg.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblReg)

    $cmbReg = New-Object System.Windows.Forms.ComboBox
    $cmbReg.Location = New-Object System.Drawing.Point(12, 294)
    $cmbReg.Size = New-Object System.Drawing.Size(480, 24)
    $cmbReg.DropDownStyle = 'DropDownList'
    foreach ($rg in @($script:WinpeRegions)) {{
        [void]$cmbReg.Items.Add($rg.label)
    }}
    $defRegIdx = 0
    for ($ri = 0; $ri -lt $script:WinpeRegions.Count; $ri++) {{
        if ($script:WinpeRegions[$ri].id -eq $script:WinpeDefaultRegionId) {{
            $defRegIdx = $ri
            break
        }}
    }}
    $cmbReg.SelectedIndex = $defRegIdx
    $form.Controls.Add($cmbReg)

    $lblKb = New-Object System.Windows.Forms.Label
    $lblKb.Text = 'Clavier / disposition'
    $lblKb.Location = New-Object System.Drawing.Point(12, 326)
    $lblKb.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblKb)

    $cmbKb = New-Object System.Windows.Forms.ComboBox
    $cmbKb.Location = New-Object System.Drawing.Point(12, 348)
    $cmbKb.Size = New-Object System.Drawing.Size(480, 24)
    $cmbKb.DropDownStyle = 'DropDownList'
    foreach ($kb in @($script:WinpeKeyboardLayouts)) {{
        [void]$cmbKb.Items.Add($kb.label)
    }}
    $defKbIdx = 0
    for ($ki = 0; $ki -lt $script:WinpeKeyboardLayouts.Count; $ki++) {{
        if ($script:WinpeKeyboardLayouts[$ki].id -eq $script:WinpeDefaultKeyboardId) {{
            $defKbIdx = $ki
            break
        }}
    }}
    $cmbKb.SelectedIndex = $defKbIdx
    $form.Controls.Add($cmbKb)

    $lblCn = New-Object System.Windows.Forms.Label
    $lblCn.Text = 'Nom de la machine (vide = defaut du master)'
    $lblCn.Location = New-Object System.Drawing.Point(12, 386)
    $lblCn.Size = New-Object System.Drawing.Size(480, 20)
    $form.Controls.Add($lblCn)

    $txtCn = New-Object System.Windows.Forms.TextBox
    $txtCn.Location = New-Object System.Drawing.Point(12, 408)
    $txtCn.Size = New-Object System.Drawing.Size(480, 24)
    $form.Controls.Add($txtCn)

    $chkU = New-Object System.Windows.Forms.CheckBox
    $chkU.Text = 'Ajouter un compte local (les comptes du master ne sont pas modifies)'
    $chkU.Location = New-Object System.Drawing.Point(12, 446)
    $chkU.Size = New-Object System.Drawing.Size(480, 24)
    $form.Controls.Add($chkU)

    $lblU = New-Object System.Windows.Forms.Label
    $lblU.Text = 'Nom utilisateur'
    $lblU.Location = New-Object System.Drawing.Point(12, 474)
    $lblU.Size = New-Object System.Drawing.Size(200, 20)
    $form.Controls.Add($lblU)

    $txtU = New-Object System.Windows.Forms.TextBox
    $txtU.Location = New-Object System.Drawing.Point(12, 494)
    $txtU.Size = New-Object System.Drawing.Size(480, 24)
    $txtU.Enabled = $false
    $form.Controls.Add($txtU)

    $lblP = New-Object System.Windows.Forms.Label
    $lblP.Text = 'Mot de passe'
    $lblP.Location = New-Object System.Drawing.Point(12, 522)
    $lblP.Size = New-Object System.Drawing.Size(200, 20)
    $form.Controls.Add($lblP)

    $txtP = New-Object System.Windows.Forms.TextBox
    $txtP.Location = New-Object System.Drawing.Point(12, 542)
    $txtP.Size = New-Object System.Drawing.Size(480, 24)
    $txtP.UseSystemPasswordChar = $true
    $txtP.Enabled = $false
    $form.Controls.Add($txtP)

    $chkU.Add_CheckedChanged({{
        $en = $chkU.Checked
        $txtU.Enabled = $en
        $txtP.Enabled = $en
    }})

    $btnOk = New-Object System.Windows.Forms.Button
    $btnOk.Text = 'Deployer'
    $btnOk.Location = New-Object System.Drawing.Point(12, 588)
    $btnOk.Size = New-Object System.Drawing.Size(230, 36)
    $btnOk.DialogResult = [System.Windows.Forms.DialogResult]::OK
    $form.AcceptButton = $btnOk
    $form.Controls.Add($btnOk)

    $btnCancel = New-Object System.Windows.Forms.Button
    $btnCancel.Text = 'Annuler'
    $btnCancel.Location = New-Object System.Drawing.Point(262, 588)
    $btnCancel.Size = New-Object System.Drawing.Size(230, 36)
    $btnCancel.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
    $form.CancelButton = $btnCancel
    $form.Controls.Add($btnCancel)

    $result = $form.ShowDialog()
    if ($result -ne [System.Windows.Forms.DialogResult]::OK) {{ return $null }}
    if ($chkU.Checked) {{
        if (-not $txtU.Text.Trim()) {{
            [System.Windows.Forms.MessageBox]::Show('Indiquez un nom d utilisateur.', 'Deploiement', 'OK', 'Warning') | Out-Null
            return $null
        }}
        if (-not $txtP.Text) {{
            [System.Windows.Forms.MessageBox]::Show('Un mot de passe est obligatoire pour creer un compte local.', 'Deploiement', 'OK', 'Warning') | Out-Null
            return $null
        }}
    }}
    if ($lstM.SelectedIndex -lt 0) {{ return $null }}
    $master = $Masters[$lstM.SelectedIndex]
    $driverKey = $null
    if ($cmbD.SelectedItem -and $cmbD.SelectedItem -ne '(aucun pilote)') {{
        $driverKey = [string]$cmbD.SelectedItem
    }}
    $lu = ''; $lp = ''
    if ($chkU.Checked) {{
        $lu = $txtU.Text.Trim()
        $lp = $txtP.Text
    }}
    $languageId = $script:WinpeDefaultUiLanguageId
    if ($cmbLang.SelectedIndex -ge 0 -and $cmbLang.SelectedIndex -lt $script:WinpeUiLanguages.Count) {{
        $languageId = $script:WinpeUiLanguages[$cmbLang.SelectedIndex].id
    }}
    $regionId = $script:WinpeDefaultRegionId
    if ($cmbReg.SelectedIndex -ge 0 -and $cmbReg.SelectedIndex -lt $script:WinpeRegions.Count) {{
        $regionId = $script:WinpeRegions[$cmbReg.SelectedIndex].id
    }}
    $keyboardId = $script:WinpeDefaultKeyboardId
    if ($cmbKb.SelectedIndex -ge 0 -and $cmbKb.SelectedIndex -lt $script:WinpeKeyboardLayouts.Count) {{
        $keyboardId = $script:WinpeKeyboardLayouts[$cmbKb.SelectedIndex].id
    }}
    return [pscustomobject]@{{
        Master = $master
        DriverProfileKey = $driverKey
        LanguageId = $languageId
        RegionId = $regionId
        KeyboardId = $keyboardId
        ComputerName = $txtCn.Text.Trim()
        LocalUser = $lu
        LocalPassword = $lp
    }}
}}

function Invoke-WinpeDeployment {{
    param($Choice)
    $wimPath = $Choice.Master.wimPath
    $dismIdx = [int]$Choice.Master.dismIndex
    if (-not (Test-Path -LiteralPath $wimPath)) {{
        throw "install.wim introuvable : $wimPath"
    }}
    Write-Host '' 
    Write-Host "Deploiement : $($Choice.Master.label)" -ForegroundColor Green
    Write-Host 'Application de l image (DISM)...' -ForegroundColor Cyan
    $dismArgs = @('/Apply-Image', "/ImageFile:$wimPath", "/Index:$dismIdx", "/ApplyDir:$TargetOS", '/CheckIntegrity', '/Verify')
    $p = Start-Process -FilePath 'dism.exe' -ArgumentList $dismArgs -Wait -PassThru -NoNewWindow
    if ($p.ExitCode -ne 0) {{ throw 'DISM /Apply-Image a echoue.' }}
    Write-Host 'Image appliquee.' -ForegroundColor Green

    if ($Choice.DriverProfileKey) {{
        $drvOk = Install-WinpeDrivers -TargetOS $TargetOS -ProfileKey $Choice.DriverProfileKey
        if (-not $drvOk) {{
            throw 'Injection pilotes echouee — verifiez le profil et les .inf sur le serveur.'
        }}
    }}

    $lpOk = Install-WinpeLanguagePacks -TargetOS $TargetOS -LanguageId $Choice.LanguageId
    if (-not $lpOk) {{
        throw 'Injection language pack echouee — verifiez les .cab sur le serveur (boot/language-packs/).'
    }}

    $unattendOk = Update-OfflineUnattend -TargetOS $TargetOS -ComputerName $Choice.ComputerName -LocalUser $Choice.LocalUser -LocalPassword $Choice.LocalPassword -LanguageId $Choice.LanguageId -RegionId $Choice.RegionId -KeyboardId $Choice.KeyboardId
    if (-not $unattendOk) {{
        throw 'Personnalisation unattend.xml echouee — verifiez les messages ci-dessus (Panther\\unattend.xml).'
    }}

    Write-Host 'Configuration demarrage UEFI (bcdboot)...' -ForegroundColor Cyan
    $p2 = Start-Process -FilePath 'bcdboot.exe' -ArgumentList @("$TargetWin", '/s', 'S:', '/f', 'uefi') -Wait -PassThru -NoNewWindow
    if ($p2.ExitCode -ne 0) {{ throw 'bcdboot a echoue.' }}

    Write-Host 'Redemarrage dans 10 secondes...' -ForegroundColor Green
    
    
}}

# --- Main ---
if (-not (Test-Path -LiteralPath $MastersFile)) {{
    Write-Host "masters.json introuvable : $MastersFile" -ForegroundColor Red
    Pause; exit 1
}}
$masters = @(Get-Content -LiteralPath $MastersFile -Raw | ConvertFrom-Json)
if (-not $masters -or $masters.Count -eq 0) {{
    Write-Host 'Aucun master.' -ForegroundColor Red
    Pause; exit 1
}}

if (-not $script:WinpeUiLanguages -or $script:WinpeUiLanguages.Count -eq 0) {{
    Write-Host 'Aucun language pack sur le serveur (boot/language-packs/).' -ForegroundColor Red
    Write-Host 'Deposez les .cab depuis l ISO Windows Languages, puis regenerez les scripts WinPE.' -ForegroundColor Yellow
    Pause; exit 1
}}

$catalog = Get-WinpeDriverCatalog
$autoKey, $hint, $score = Try-DetectDriverProfile -Catalog $catalog
$requireManual = -not $autoKey

$choice = Show-WinpeDeployWizard -Masters $masters -Catalog $catalog -AutoDriverKey $autoKey -DriverHint $hint -RequireManualDriver $requireManual
if (-not $choice) {{
    Write-Host 'Operation annulee.' -ForegroundColor Yellow
    exit 1
}}

try {{
    Invoke-WinpeDeployment -Choice $choice
}} catch {{
    Write-Host $_.Exception.Message -ForegroundColor Red
    Pause
    exit 1
}}
"""
