"""
Génération des scripts WinPE (PowerShell + startnet.cmd minimal) sur le partage HTTP/SMB.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path

from app.config import settings
from app.models.models import IsoVersion, WinpeInstall
from app.services.winpe_installs import (
    INSTALL_WIM_FILENAME,
    install_wim_path,
    installs_root,
    smb_connect_host_for_winpe,
    smb_host_from_settings,
    smb_share_name,
    version_segment,
)
from app.services.winpe_ps_lib import ps_deploy_wizard, ps_inject_drivers_lib
from app.services.winpe_wim import (
    STARTNET_WIM_PATH,
    boot_wim_filesystem_path,
    run_wimupdate_add,
)

logger = logging.getLogger(__name__)

SCRIPTS_DIRNAME = "scripts"
DEPLOY_PS1 = "deploy.ps1"
INJECT_DRIVERS_PS1 = "inject-drivers.ps1"
MASTERS_JSON = "masters.json"


def scripts_dir(version: IsoVersion) -> Path:
    os_slug = version.os_type.slug
    seg = version_segment(version)
    path = settings.boot_dir / os_slug / seg / SCRIPTS_DIRNAME
    path.mkdir(parents=True, exist_ok=True)
    return path


def z_boot_prefix(version: IsoVersion) -> str:
    """Préfixe sous le lecteur Z: (racine = partage [boot])."""
    os_slug = version.os_type.slug
    seg = version_segment(version)
    return f"{os_slug}\\{seg}"


def z_scripts_dir(version: IsoVersion) -> str:
    return f"Z:\\{z_boot_prefix(version)}\\{SCRIPTS_DIRNAME}"


def z_drivers_root() -> str:
    return "Z:\\drivers"


def z_language_packs_root() -> str:
    return "Z:\\language-packs"


def build_masters_catalog(
    version: IsoVersion, installs: list[WinpeInstall]
) -> list[dict]:
    prefix = z_boot_prefix(version)
    rows: list[dict] = []
    by_slug: dict[str, WinpeInstall] = {}
    for wi in installs:
        slug = (wi.slug or "").strip()
        if not slug:
            continue
        by_slug[slug] = wi

    # Source de vérité: les dossiers réels sur disque.
    # Si 2 dossiers existent sous installs/, on génère 2 lignes dans masters.json.
    root = installs_root(version)
    if root.is_dir():
        slugs = sorted(
            [
                p.name
                for p in root.iterdir()
                if p.is_dir() and (p / INSTALL_WIM_FILENAME).is_file()
            ],
            key=str.casefold,
        )
    else:
        slugs = sorted(by_slug.keys(), key=str.casefold)

    for slug in slugs:
        wi = by_slug.get(slug)
        raw_label = (wi.label if wi else "") or slug
        label = " ".join(str(raw_label).replace("\r", " ").replace("\n", " ").replace("\t", " ").split()) or slug
        wim_index = max(1, int((wi.wim_index if wi else 1) or 1))
        rows.append(
            {
                "slug": slug,
                "label": label,
                "wimPath": f"Z:\\{prefix}\\installs\\{slug}\\{INSTALL_WIM_FILENAME}",
                "dismIndex": wim_index,
            }
        )

    # Masters globaux persistants : Z:\masters\<slug>\install.wim
    try:
        from app.services.winpe_master_store import list_global_masters

        existing = {r["slug"] for r in rows}
        for gm in list_global_masters():
            slug = str(gm.get("key") or gm.get("slug") or "").strip()
            if not slug or slug in existing:
                continue
            wim_rel = slug.replace("/", "\\")
            rows.append(
                {
                    "slug": slug,
                    "label": str(gm.get("label") or slug).strip() or slug,
                    "wimPath": f"Z:\\masters\\{wim_rel}\\{INSTALL_WIM_FILENAME}",
                    "dismIndex": max(1, int(gm.get("wim_index") or 1)),
                }
            )
            existing.add(slug)
    except Exception:
        logger.debug("Masters globaux indisponibles pour le catalogue WinPE", exc_info=True)
    return rows


def generate_masters_json(version: IsoVersion, installs: list[WinpeInstall]) -> str:
    return json.dumps(build_masters_catalog(version, installs), ensure_ascii=False, indent=2)


def generate_deploy_ps1(version: IsoVersion) -> str:
    scripts = z_scripts_dir(version)
    return ps_deploy_wizard(scripts, MASTERS_JSON)


def generate_inject_drivers_ps1(version: IsoVersion) -> str:
    drivers_json = f"{z_drivers_root()}\\drivers.json"
    lp_json = f"{z_language_packs_root()}\\language-packs.json"
    return ps_inject_drivers_lib(
        drivers_json,
        z_drivers_root(),
        language_packs_json=lp_json,
        language_packs_root=z_language_packs_root(),
    )


def generate_startnet_cmd(version: IsoVersion) -> str:
    host = smb_connect_host_for_winpe()
    share = smb_share_name()
    deploy_ps1 = f"{z_scripts_dir(version)}\\{DEPLOY_PS1}"
    unc = f"\\\\{host}\\{share}"

    return f"""@echo off
setlocal EnableDelayedExpansion
REM Generated by iPXE Manager — lance les scripts PowerShell sur le partage boot
wpeinit
echo Mode performances elevees...
powercfg -setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c >nul 2>&1
if errorlevel 1 powercfg -setactive e6a491b6-4137-48e2-b521-de7b3d8b8c8d >nul 2>&1
echo Desactivation du pare-feu Windows...
netsh advfirewall set allprofiles state off >nul 2>&1
if errorlevel 1 netsh firewall set opmode disable >nul 2>&1
echo Preparation disque UEFI (GPT) sur le disque 0...
set "_DP=X:\ipxe-diskpart.txt"
> "%_DP%" (
echo select disk 0
echo clean
echo convert gpt
echo create partition efi size=100
echo format quick fs=fat32 label="System"
echo assign letter=S
echo create partition msr size=16
echo create partition primary
echo format quick fs=ntfs label="Windows"
echo assign letter=W
echo exit
)
diskpart /s "%_DP%"
set "_DPE=%errorlevel%"
del "%_DP%" >nul 2>&1
if not "%_DPE%"=="0" (
  echo diskpart a echoue.
  pause
  goto :eof
)
echo Fin diskpart — reinitialisation reseau...
wpeutil InitializeNetwork >nul 2>&1
wpeutil WaitForNetwork
net start rdr >nul 2>&1
net start mrxsmb20 >nul 2>&1
net start mrxsmb10 >nul 2>&1
net start workstation >nul 2>&1
echo Attente serveur {host} (3 pings OK + pause)...
call :wait_host_ready
net use Z: /delete /y >nul 2>&1
net use \\\\{host}\\IPC$ /user:guest >nul 2>&1
echo Montage du partage boot...
echo Commande : net use Z: {unc} /user:guest
set "_SMB_TRY=0"
:mount_boot_retry
set /a _SMB_TRY+=1
call :wait_host_ready
net use Z: {unc} /user:guest
if not errorlevel 1 goto mount_boot_ok
echo Tentative !_SMB_TRY!/20 echouee (erreur %errorlevel%, 53 = SMB pas pret).
if !_SMB_TRY! lss 20 goto mount_boot_retry
echo Echec montage SMB {unc}
echo Test manuel : net use Z: {unc} /user:guest
pause
goto :eof

REM 3 pings reussis vers le serveur puis pause (~8 s) avant net use
:wait_host_ready
set "_PING_OK=0"
:wait_host_ping_one
ping -n 1 -w 2000 {host} >nul
if errorlevel 1 (
  set "_PING_OK=0"
  call :ipxe_ping_host 3
  goto wait_host_ping_one
)
set /a _PING_OK+=1
if !_PING_OK! lss 3 goto wait_host_ping_one
call :ipxe_ping_host 8
exit /b 0

REM N pings vers le serveur (~1 s entre chaque)
:ipxe_ping_host
ping -n %1 -w 1000 {host} >nul 2>&1
exit /b 0

:mount_boot_ok
echo Partage monte sur Z:
if not exist "{deploy_ps1}" (
  echo Script deploy.ps1 introuvable : {deploy_ps1}
  echo Regenerer les scripts WinPE depuis iPXE Manager.
  pause
  goto :eof
)
echo Lancement du deploiement PowerShell...
powershell -NoLogo -NoProfile -ExecutionPolicy Bypass -File "{deploy_ps1}"
if errorlevel 1 (
  echo Le script de deploiement a signale une erreur.
  pause
)
net use Z: /delete /y >nul 2>&1
"""


def write_all_scripts(version: IsoVersion, installs: list[WinpeInstall]) -> Path:
    """Écrit masters.json, deploy.ps1, inject-drivers.ps1 sur le disque."""
    try:
        from app.services.winpe_language_packs import rebuild_catalog

        rebuild_catalog()
    except OSError as exc:
        logger.warning("language-packs.json non mis a jour : %s", exc)

    sdir = scripts_dir(version)
    (sdir / MASTERS_JSON).write_text(
        generate_masters_json(version, installs) + "\n",
        encoding="utf-8",
    )
    (sdir / DEPLOY_PS1).write_text(generate_deploy_ps1(version), encoding="utf-8-sig")
    (sdir / INJECT_DRIVERS_PS1).write_text(
        generate_inject_drivers_ps1(version), encoding="utf-8-sig"
    )
    logger.info("Scripts WinPE écrits dans %s (%d master(s))", sdir, len(installs))
    return sdir


def inject_startnet_into_boot_wim(version: IsoVersion) -> Path:
    """Injecte le startnet.cmd minimal dans boot.wim."""
    boot_wim = boot_wim_filesystem_path(version)
    bak = boot_wim.with_suffix(".wim.bak")
    if not bak.is_file():
        import shutil

        shutil.copy2(boot_wim, bak)

    boot_image_index = int(getattr(settings, "winpe_boot_wim_index", 1) or 1)
    content = generate_startnet_cmd(version)

    import tempfile

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".cmd",
        delete=False,
        encoding="utf-8",
        newline="\r\n",
    ) as tf:
        tf.write(content)
        cmd_path = Path(tf.name)

    try:
        src = str(cmd_path.resolve())
        dest_in_wim = "/" + STARTNET_WIM_PATH.replace("\\", "/").lstrip("/")
        proc = run_wimupdate_add(boot_wim, boot_image_index, src, dest_in_wim)
    finally:
        cmd_path.unlink(missing_ok=True)

    if proc.returncode != 0:
        from app.services.iso_extractor import ExtractionError

        tail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-3000:]
        raise ExtractionError(
            f"wimupdate startnet.cmd échoué (code {proc.returncode}) : {tail}"
        )
    return boot_wim


def _sync_windows_boot_paths(version: IsoVersion) -> None:
    """Aligne BDD (casse SOURCES/BOOT.WIM) sur les fichiers réels avant wimupdate."""
    be = version.boot_entry
    if not be or (version.os_type.boot_type or "").lower() != "windows":
        return
    from app.services.windows_boot_paths import (
        sync_windows_boot_entry_from_disk,
        version_slug_for_disk,
    )

    seg = version_slug_for_disk(be, version.version_label, version.id)
    sync_windows_boot_entry_from_disk(be, version.os_type.slug, seg)


def regenerate_winpe_deployment(
    version: IsoVersion, installs: list[WinpeInstall], *, patch_wim: bool = True
) -> dict:
    """
    Régénère scripts + optionnellement startnet.cmd dans boot.wim.
    """
    if not installs:
        raise ValueError("Ajoutez au moins un master (install.wim) avant de générer les scripts.")
    _sync_windows_boot_paths(version)
    if patch_wim:
        boot_wim_filesystem_path(version)
    sdir = write_all_scripts(version, installs)
    if patch_wim:
        inject_startnet_into_boot_wim(version)
    return {
        "scripts_dir": str(sdir),
        "masters": len(build_masters_catalog(version, installs)),
        "patched_at": datetime.utcnow().isoformat() + "Z",
    }
