"""
Génère et injecte ``startnet.cmd`` dans ``boot.wim`` (wimlib ``wimupdate``).
"""
from __future__ import annotations

import logging
import shlex
import shutil
import subprocess
import tempfile
from pathlib import Path

from app.config import settings
from app.models.models import IsoVersion, WinpeInstall
from app.services.iso_extractor import ExtractionError
from app.services.winpe_installs import (
    install_wim_path,
    install_wim_rel_path,
    smb_host_from_settings,
    smb_share_name,
    version_segment,
)

logger = logging.getLogger(__name__)

STARTNET_WIM_PATH = "Windows/System32/startnet.cmd"


def _wimupdate_argv(wim_file: str, image_index: int) -> list[str]:
    """
    argv pour injecter dans une WIM : ``wimupdate WIM INDEX`` ou
    ``wimlib-imagex update WIM INDEX`` (sans « update », code 255 + Usage).
    """
    wu = shutil.which("wimupdate")
    if wu:
        return [wu, wim_file, str(image_index)]
    wi = shutil.which("wimlib-imagex")
    if wi:
        return [wi, "update", wim_file, str(image_index)]
    raise ExtractionError(
        "wimupdate / wimlib-imagex introuvable — apt install wimtools"
    )


def _run_wimupdate_add(
    boot_wim: Path,
    image_index: int,
    src: str,
    dest_in_wim: str,
) -> subprocess.CompletedProcess[str]:
    """Exécute « add SOURCE DEST » via fichier de commandes (man wimupdate)."""
    add_line = f"add {shlex.quote(src)} {shlex.quote(dest_in_wim)}\n"
    one_cmd = f"add {shlex.quote(src)} {shlex.quote(dest_in_wim)}"
    wim_str = str(boot_wim.resolve())
    attempts: list[list[str]] = [_wimupdate_argv(wim_str, image_index)]
    # WIM à une seule image : index parfois omis
    wu = shutil.which("wimupdate")
    if wu:
        attempts.append([wu, wim_str])
    wi = shutil.which("wimlib-imagex")
    if wi:
        attempts.append([wi, "update", wim_str])

    last: subprocess.CompletedProcess[str] | None = None
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".wimupdate.txt",
        delete=False,
        encoding="utf-8",
    ) as uf:
        uf.write(add_line)
        uf.flush()
        update_cmd_path = Path(uf.name)

    try:
        for base_argv in attempts:
            with open(update_cmd_path, encoding="utf-8") as cmdf:
                last = subprocess.run(
                    base_argv,
                    stdin=cmdf,
                    capture_output=True,
                    text=True,
                    timeout=600,
                )
            if last.returncode == 0:
                return last
            last = subprocess.run(
                base_argv + ["--command", one_cmd],
                capture_output=True,
                text=True,
                timeout=600,
            )
            if last.returncode == 0:
                return last
        assert last is not None
        return last
    finally:
        try:
            update_cmd_path.unlink(missing_ok=True)
        except OSError:
            pass


def boot_wim_filesystem_path(version: IsoVersion) -> Path:
    be = version.boot_entry
    if not be or not (be.boot_wim_path or "").strip():
        raise FileNotFoundError(
            "boot.wim absent — extrayez l'ISO WinPE ou uploadez boot.wim avant de choisir une install.wim."
        )
    rel = be.boot_wim_path.replace("\\", "/").lstrip("/")
    path = Path(settings.http_root) / rel
    if not path.is_file():
        raise FileNotFoundError(f"boot.wim introuvable sur le disque : {path}")
    return path


def generate_startnet_cmd(version: IsoVersion, install: WinpeInstall) -> str:
    """
    Script WinPE : wpeinit, partitionnement GPT UEFI (S: EFI, W: Windows),
    montage SMB, DISM Apply-Image sur W:\\, bcdboot UEFI puis reboot.
    """
    host = smb_host_from_settings()
    share = smb_share_name()
    rel = install_wim_rel_path(version, install.slug)
    # Chemin vu après « net use Z: \\host\boot »
    win_rel = rel.replace("/", "\\")
    if win_rel.lower().startswith("boot\\"):
        win_rel = win_rel[5:]
    wim_on_z = f"Z:\\{win_rel}"
    idx = max(1, int(install.wim_index or 1))

    return f"""@echo off
REM Generated by iPXE Manager — {install.label or install.slug}
REM Install: {install.slug} — index DISM {idx}
wpeinit
echo Preparation disque UEFI (GPT) sur le disque 0...
(
echo select disk 0
echo clean
echo convert gpt
echo create partition efi size=100
echo format quick fs=fat32 label="System"
echo assign letter=S
echo create partition msr size=16
echo create partition primary
echo format quick fs=ntfs label="Windows"
echo assign letter=W
) | diskpart
if errorlevel 1 (
  echo diskpart a echoue.
  pause
  goto :eof
)
net use Z: \\\\{host}\\{share} /user:guest ""
if errorlevel 1 (
  echo Echec montage SMB \\\\{host}\\{share}
  pause
  goto :eof
)
set WIM={wim_on_z}
if not exist "%WIM%" (
  echo install.wim introuvable: %WIM%
  echo Verifiez Samba [{share}] et le dossier installs/{install.slug}/
  pause
  goto :eof
)
echo Application de %WIM% vers W:\\ (index {idx}) ...
Dism /Apply-Image /ImageFile:"%WIM%" /Index:{idx} /ApplyDir:W:\\ /CheckIntegrity /Verify
if errorlevel 1 (
  echo DISM /Apply-Image a echoue.
  pause
  goto :eof
)
echo Configuration du demarrage UEFI...
bcdboot W:\\Windows /s S: /f uefi
if errorlevel 1 (
  echo bcdboot a echoue.
  pause
  goto :eof
)
echo Image appliquee. Redemarrage dans 10 secondes...
timeout /t 10 /nobreak >nul
wpeutil reboot
"""


def patch_boot_wim_startnet(
    version: IsoVersion,
    install: WinpeInstall,
    *,
    image_index: int | None = None,
) -> Path:
    """
    Sauvegarde boot.wim en .bak si besoin, injecte startnet.cmd via wimupdate.
    Retourne le chemin du boot.wim modifié.
    """
    boot_wim = boot_wim_filesystem_path(version)
    bak = boot_wim.with_suffix(".wim.bak")
    if not bak.is_file():
        shutil.copy2(boot_wim, bak)
        logger.info("Sauvegarde boot.wim → %s", bak)

    idx = image_index if image_index is not None else max(1, int(install.wim_index or 1))
    wim_idx = getattr(settings, "winpe_boot_wim_index", 1) or 1
    # Index dans boot.wim (souvent 1 = Windows PE) ; wim_idx configurable
    boot_image_index = int(wim_idx)

    content = generate_startnet_cmd(version, install)

    if not install_wim_path(version, install.slug).is_file():
        raise FileNotFoundError(
            f"install.wim manquant pour « {install.slug} » — uploadez le fichier d'abord."
        )

    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".cmd",
        delete=False,
        encoding="utf-8",
        newline="\r\n",
    ) as tf:
        tf.write(content)
        tf.flush()
        cmd_path = Path(tf.name)

    try:
        src = str(cmd_path.resolve())
        dest_in_wim = "/" + STARTNET_WIM_PATH.replace("\\", "/").lstrip("/")
        proc = _run_wimupdate_add(boot_wim, boot_image_index, src, dest_in_wim)
    finally:
        try:
            cmd_path.unlink(missing_ok=True)
        except OSError:
            pass

    if proc.returncode != 0:
        tail = ((proc.stdout or "") + (proc.stderr or "")).strip()[-3000:]
        raise ExtractionError(
            f"wimupdate a échoué (code {proc.returncode}) pour {boot_wim} "
            f"(image index {boot_image_index}) :\n{tail}"
        )

    logger.info(
        "startnet.cmd injecté dans %s (image %s) pour install %s",
        boot_wim,
        boot_image_index,
        install.slug,
    )
    return boot_wim


def activate_winpe_install(version: IsoVersion, install: WinpeInstall) -> None:
    """Point d'entrée : patch boot.wim pour l'install choisie."""
    patch_boot_wim_startnet(version, install)
