# Traductions WinPE par clé i18n (de, es, it, pt)
WINPE: dict[str, tuple[str, str, str, str]] = {
    "iso.detail.winpe_th_index": ("Index", "Índice", "Indice", "Índice"),
    "iso.winpe_drivers_title": ("Treiber", "Controladores", "Driver", "Controladores"),
    "iso.winpe_drivers_intro": (
        "Laden Sie ein Treiber-ZIP hoch (z. B. VirtIO-Paket): Extraktion nach boot/drivers/<type>/ im Hintergrund.",
        "Suba un ZIP de controladores (p. ej. pack VirtIO): se extrae en boot/drivers/<type>/ en segundo plano.",
        "Caricate uno ZIP di driver (es. pack VirtIO): estrazione in boot/drivers/<type>/ in background.",
        "Envie um ZIP de controladores (ex. pack VirtIO): extração para boot/drivers/<type>/ em segundo plano.",
    ),
    "iso.winpe_drivers_smb": ("SMB-Treiberzugriff", "Acceso SMB controladores", "Accesso SMB driver", "Acesso SMB controladores"),
    "iso.winpe_drivers_machine": ("Maschinentyp", "Tipo de máquina", "Tipo macchina", "Tipo de máquina"),
    "iso.winpe_drivers_existing": ("Vorhandener Typ", "Tipo existente", "Tipo esistente", "Tipo existente"),
    "iso.winpe_drivers_new": ("Anderer Maschinentyp", "Otro tipo de máquina", "Altro tipo macchina", "Outro tipo de máquina"),
    "iso.winpe_drivers_new_name": ("Name des neuen Typs", "Nombre del nuevo tipo", "Nome del nuovo tipo", "Nome do novo tipo"),
    "iso.winpe_drivers_new_ph": ("z. B. Lenovo, Dell OptiPlex", "p. ej. Lenovo, Dell OptiPlex", "es. Lenovo, Dell OptiPlex", "ex. Lenovo, Dell OptiPlex"),
    "iso.winpe_drivers_files": ("ZIP-Archiv", "Archivo ZIP", "Archivio ZIP", "Arquivo ZIP"),
    "iso.winpe_drivers_files_hint": (
        "ZIP mit .inf-Dateien (und zugehörigen .sys, .cat). Ordnerstruktur im ZIP bleibt erhalten.",
        "ZIP con archivos .inf (y .sys, .cat asociados). Se conserva la estructura de carpetas del ZIP.",
        "ZIP con file .inf (e .sys, .cat associati). La struttura delle cartelle nel ZIP è conservata.",
        "ZIP com ficheiros .inf (e .sys, .cat associados). A estrutura de pastas no ZIP é preservada.",
    ),
    "iso.winpe_drivers_upload": ("ZIP hochladen", "Subir ZIP", "Carica ZIP", "Enviar ZIP"),
    "iso.winpe_drivers_uploaded": ("Treiber gespeichert — Katalog aktualisiert.", "Controladores guardados — catálogo actualizado.", "Driver salvati — catalogo aggiornato.", "Controladores guardados — catálogo atualizado."),
    "iso.winpe_drivers_zip_started": ("ZIP empfangen — Extraktion im Hintergrund…", "ZIP recibido — extrayendo en segundo plano…", "ZIP ricevuto — estrazione in background…", "ZIP recebido — a extrair em segundo plano…"),
    "iso.winpe_drivers_zip_extract": ("Treiber werden auf dem Server extrahiert…", "Extrayendo controladores en el servidor…", "Estrazione driver sul server…", "A extrair controladores no servidor…"),
    "iso.winpe_drivers_zip_done": ("Treiber extrahiert — Katalog aktualisiert.", "Controladores extraídos — catálogo actualizado.", "Driver estratti — catalogo aggiornato.", "Controladores extraídos — catálogo atualizado."),
    "iso.winpe_drivers_zip_error": ("Treiber-ZIP-Extraktion fehlgeschlagen.", "Error al extraer el ZIP de controladores.", "Estrazione ZIP driver fallita.", "Falha na extração do ZIP de controladores."),
    "iso.winpe_drivers_zip_only": ("Wählen Sie eine .zip-Datei.", "Seleccione un archivo .zip.", "Selezionare un file .zip.", "Selecione um ficheiro .zip."),
    "iso.winpe_drivers_zip_empty": ("Leeres ZIP-Archiv.", "Archivo ZIP vacío.", "Archivio ZIP vuoto.", "Arquivo ZIP vazio."),
    "iso.winpe_drivers_no_files": ("Wählen Sie ein ZIP-Archiv.", "Seleccione un archivo ZIP.", "Selezionare un archivio ZIP.", "Selecione um arquivo ZIP."),
    "iso.winpe_drivers_catalog": ("Registrierte Maschinentypen", "Tipos de máquina registrados", "Tipi macchina registrati", "Tipos de máquina registados"),
    "iso.winpe_drivers_count": ("Dateien", "archivos", "file", "ficheiros"),
    "iso.winpe_drivers_path": ("Pfad", "Ruta", "Percorso", "Caminho"),
    "iso.winpe_drivers_progress": ("Treiber werden hochgeladen…", "Subiendo controladores…", "Caricamento driver…", "A enviar controladores…"),
    "iso.winpe_install_title": ("WinPE-Bereitstellungen (install.wim)", "Despliegues WinPE (install.wim)", "Distribuzioni WinPE (install.wim)", "Implementações WinPE (install.wim)"),
    "iso.winpe_install_intro": (
        "Masters können lokal zu dieser Version (boot/<os>/<version>/installs/<name>/install.wim) oder persistent global (boot/masters/<family>/<name>/install.wim) sein. Auswahl im WinPE-Assistenten deploy.ps1.",
        "Los masters pueden ser locales a esta versión (boot/<os>/<version>/installs/<name>/install.wim) o globales persistentes (boot/masters/<family>/<name>/install.wim). La selección ocurre en deploy.ps1.",
        "I master possono essere locali a questa versione (boot/<os>/<version>/installs/<name>/install.wim) o globali persistenti (boot/masters/<family>/<name>/install.wim). La scelta avviene in deploy.ps1.",
        "Os masters podem ser locais a esta versão (boot/<os>/<version>/installs/<name>/install.wim) ou globais persistentes (boot/masters/<family>/<name>/install.wim). A seleção ocorre em deploy.ps1.",
    ),
    "iso.winpe_install_slug": ("Lokaler Ordnername (Kennung)", "Nombre de carpeta local (identificador)", "Nome cartella locale (identificatore)", "Nome da pasta local (identificador)"),
    "iso.winpe_install_label": ("Anzeigename", "Etiqueta mostrada", "Etichetta visualizzata", "Etiqueta apresentada"),
    "iso.winpe_install_wim_index": ("DISM-Index in install.wim", "Índice DISM en install.wim", "Indice DISM in install.wim", "Índice DISM em install.wim"),
    "iso.winpe_install_file": ("install.wim-Datei", "Archivo install.wim", "File install.wim", "Ficheiro install.wim"),
    "iso.winpe_install_add": ("Image hinzufügen", "Añadir imagen", "Aggiungi immagine", "Adicionar imagem"),
    "iso.winpe_install_select": ("Aktives Installationsimage", "Imagen de instalación activa", "Immagine di installazione attiva", "Imagem de instalação ativa"),
    "iso.winpe_install_apply": ("boot.wim patchen (startnet.cmd)", "Parchear boot.wim (startnet.cmd)", "Patch boot.wim (startnet.cmd)", "Aplicar patch boot.wim (startnet.cmd)"),
    "iso.winpe_install_clear": ("Aktives Image entfernen", "Quitar imagen activa", "Rimuovi immagine attiva", "Remover imagem ativa"),
    "iso.winpe_install_current": ("Aktives Image", "Imagen activa", "Immagine attiva", "Imagem ativa"),
    "iso.winpe_install_smb": ("SMB-Zugriff (WinPE-Lesen)", "Acceso SMB (lectura WinPE)", "Accesso SMB (lettura WinPE)", "Acesso SMB (leitura WinPE)"),
    "iso.winpe_install_list": ("Verfügbare Images", "Imágenes disponibles", "Immagini disponibili", "Imagens disponíveis"),
    "iso.winpe_install_delete_confirm": ("Lokales Image {slug} löschen?", "¿Eliminar imagen local {slug}?", "Eliminare immagine locale {slug}?", "Eliminar imagem local {slug}?"),
    "iso.winpe_install_ok": ("Lokaler Master gespeichert — WinPE-Skripte werden aktualisiert…", "Master local guardado — actualizando scripts WinPE…", "Master locale salvato — aggiornamento script WinPE…", "Master local guardado — a atualizar scripts WinPE…"),
    "iso.winpe_install_ready": (
        "Lokaler Master gespeichert. masters.json, deploy.ps1 und startnet.cmd sind aktuell. Beim PXE-Boot bietet deploy.ps1 verfügbare Masters (lokal + global).",
        "Master local guardado. masters.json, deploy.ps1 y startnet.cmd están actualizados. En el arranque PXE, deploy.ps1 ofrece los masters disponibles (locales + globales).",
        "Master locale salvato. masters.json, deploy.ps1 e startnet.cmd sono aggiornati. Al boot PXE, deploy.ps1 propone i master disponibili (locali + globali).",
        "Master local guardado. masters.json, deploy.ps1 e startnet.cmd estão atualizados. No arranque PXE, deploy.ps1 oferece os masters disponíveis (locais + globais).",
    ),
    "iso.winpe_install_partial": (
        "Lokaler Master gespeichert. Skriptaktualisierung dauert länger als erwartet — klicken Sie auf « WinPE-Skripte und boot.wim aktualisieren », wenn die Warnung bleibt.",
        "Master local guardado. La actualización de scripts tarda más de lo previsto — pulse « Actualizar scripts WinPE y boot.wim » si la advertencia persiste.",
        "Master locale salvato. L'aggiornamento script richiede più tempo del previsto — fare clic su « Aggiorna script WinPE e boot.wim » se l'avviso resta.",
        "Master local guardado. A atualização dos scripts demora mais do que o esperado — clique em « Atualizar scripts WinPE e boot.wim » se o aviso persistir.",
    ),
    "iso.winpe_install_not_found": ("Installationsimage nicht gefunden.", "Imagen de instalación no encontrada.", "Immagine di installazione non trovata.", "Imagem de instalação não encontrada."),
    "iso.winpe_scripts_title": ("WinPE-Skripte (PowerShell)", "Scripts WinPE (PowerShell)", "Script WinPE (PowerShell)", "Scripts WinPE (PowerShell)"),
    "iso.winpe_scripts_intro": (
        "deploy.ps1 (Assistent: Master, Treiber, PC-Name, lokaler Benutzer) und inject-drivers.ps1 (Bibliothek) werden auf der Boot-Freigabe erzeugt. startnet.cmd bereitet die Platte vor, mountet SMB und startet deploy.ps1.",
        "deploy.ps1 (asistente: master, controladores, nombre PC, usuario local) e inject-drivers.ps1 (biblioteca) se generan en el recurso de arranque. startnet.cmd prepara el disco, monta SMB y ejecuta deploy.ps1.",
        "deploy.ps1 (procedura guidata: master, driver, nome PC, utente locale) e inject-drivers.ps1 (libreria) sono generati sulla condivisione boot. startnet.cmd prepara il disco, monta SMB ed esegue deploy.ps1.",
        "deploy.ps1 (assistente: master, controladores, nome PC, utilizador local) e inject-drivers.ps1 (biblioteca) são gerados na partilha de arranque. startnet.cmd prepara o disco, monta SMB e executa deploy.ps1.",
    ),
    "iso.winpe_scripts_help": (
        "Nach Hinzufügen/Entfernen eines Masters (lokal oder global) oder Treiberpakets neu erzeugen.",
        "Regenerar tras añadir/eliminar cualquier master (local o global) o paquete de controladores.",
        "Rigenerare dopo aver aggiunto/rimosso un master (locale o globale) o un pacchetto driver.",
        "Regenerar após adicionar/remover qualquer master (local ou global) ou pacote de controladores.",
    ),
    "iso.winpe_scripts_regenerate": ("WinPE-Skripte und boot.wim aktualisieren", "Actualizar scripts WinPE y boot.wim", "Aggiorna script WinPE e boot.wim", "Atualizar scripts WinPE e boot.wim"),
    "iso.winpe_scripts_queued": ("WinPE-Skripte werden erzeugt (Celery)…", "Generando scripts WinPE (Celery)…", "Generazione script WinPE (Celery)…", "A gerar scripts WinPE (Celery)…"),
    "iso.winpe_scripts_polling": ("Erstellung läuft — Seite aktualisiert sich bei Fertigstellung.", "Generación en curso — la página se actualizará al terminar.", "Generazione in corso — la pagina si aggiornerà al termine.", "Geração em curso — a página atualiza quando terminar."),
    "iso.winpe_scripts_done": ("WinPE-Skripte und boot.wim erfolgreich aktualisiert.", "Scripts WinPE y boot.wim actualizados correctamente.", "Script WinPE e boot.wim aggiornati con successo.", "Scripts WinPE e boot.wim atualizados com sucesso."),
    "iso.winpe_scripts_failed": ("Erstellung fehlgeschlagen — Celery-Logs prüfen (ipxe-celery).", "Generación fallida — consulte los logs Celery (ipxe-celery).", "Generazione fallita — controllare i log Celery (ipxe-celery).", "Geração falhou — verifique os logs Celery (ipxe-celery)."),
    "iso.winpe_scripts_last": ("Skripte erzeugt", "Scripts generados", "Script generati", "Scripts gerados"),
    "iso.winpe_scripts_no_masters": ("Mindestens einen Master (install.wim) hinzufügen, bevor Skripte erzeugt werden.", "Añada al menos un master (install.wim) antes de generar scripts.", "Aggiungere almeno un master (install.wim) prima di generare gli script.", "Adicione pelo menos um master (install.wim) antes de gerar scripts."),
    "iso.winpe_language_packs_title": ("Sprachpakete (UI-Sprache)", "Paquetes de idioma (idioma de interfaz)", "Language pack (lingua interfaccia)", "Pacotes de idioma (idioma da interface)"),
    "iso.winpe_language_packs_intro": (
        "Laden Sie .cab-Dateien hoch (Windows Languages ISO): Locale wird aus dem Dateinamen gelesen. Mehrere Sprachen in einem Upload.",
        "Suba archivos .cab (ISO Windows Languages): la configuración regional se lee del nombre del archivo. Varios idiomas en un solo envío.",
        "Caricate file .cab (ISO Windows Languages): la locale è letta dal nome file. Più lingue in un solo caricamento.",
        "Envie ficheiros .cab (ISO Windows Languages): a locale é lida do nome do ficheiro. Vários idiomas num único envio.",
    ),
    "iso.winpe_language_packs_smb": ("SMB-Zugriff Sprachpakete", "Acceso SMB paquetes de idioma", "Accesso SMB language pack", "Acesso SMB pacotes de idioma"),
    "iso.winpe_language_packs_existing": ("Vorhandene Locale", "Configuración regional existente", "Locale esistente", "Locale existente"),
    "iso.winpe_language_packs_new": ("Neue Locale", "Nueva configuración regional", "Nuova locale", "Nova locale"),
    "iso.winpe_language_packs_new_id": ("Sprachkennung", "Identificador de idioma", "Identificatore lingua", "Identificador de idioma"),
    "iso.winpe_language_packs_new_ph": ("z. B. en-US, de-DE, es-ES", "p. ej. en-US, de-DE, es-ES", "es. en-US, de-DE, es-ES", "ex. en-US, de-DE, es-ES"),
    "iso.winpe_language_packs_files": (".cab-Dateien", "Archivos .cab", "File .cab", "Ficheiros .cab"),
    "iso.winpe_language_packs_files_hint": (
        "Mehrfachauswahl ohne Dateilimit: fr-FR, en-US, de-DE usw. werden automatisch aus dem Dateinamen sortiert.",
        "Selección múltiple sin límite: fr-FR, en-US, de-DE, etc. se ordenan automáticamente según el nombre del archivo.",
        "Selezione multipla senza limite: fr-FR, en-US, de-DE, ecc. sono ordinati automaticamente dal nome file.",
        "Seleção múltipla sem limite: fr-FR, en-US, de-DE, etc. são ordenados automaticamente pelo nome do ficheiro.",
    ),
    "iso.winpe_language_packs_skipped": ("Datei(en) übersprungen (Locale im Dateinamen nicht erkannt)", "archivo(s) omitido(s) (configuración regional no reconocida en el nombre)", "file saltati (locale non riconosciuta nel nome)", "ficheiro(s) ignorado(s) (locale não reconhecida no nome)"),
    "iso.winpe_language_packs_skipped_detail": ("Locale nicht erkannt", "Configuración regional no reconocida", "Locale non riconosciuta", "Locale não reconhecida"),
    "iso.winpe_language_packs_empty_files": ("Leere oder unlesbare Datei(en)", "Archivo(s) vacío(s) o ilegible(s)", "File vuoti o illeggibili", "Ficheiro(s) vazio(s) ou ilegível(is)"),
    "iso.winpe_language_packs_upload_summary": ("Sprachpakete gespeichert", "Paquetes de idioma guardados", "Language pack salvati", "Pacotes de idioma guardados"),
    "iso.winpe_language_packs_upload": ("Sprachpakete hochladen", "Subir paquetes de idioma", "Carica language pack", "Enviar pacotes de idioma"),
    "iso.winpe_language_packs_uploaded": ("Sprachpakete gespeichert — Katalog aktualisiert. WinPE-Skripte neu erzeugen.", "Paquetes guardados — catálogo actualizado. Regenerar scripts WinPE.", "Language pack salvati — catalogo aggiornato. Rigenerare script WinPE.", "Pacotes guardados — catálogo atualizado. Regenerar scripts WinPE."),
    "iso.winpe_language_packs_no_files": ("Mindestens eine .cab-Datei wählen.", "Seleccione al menos un archivo .cab.", "Selezionare almeno un file .cab.", "Selecione pelo menos um ficheiro .cab."),
    "iso.winpe_language_packs_catalog": ("Sprachen beim Bereitstellen verfügbar", "Idiomas disponibles en el despliegue", "Lingue disponibili al deploy", "Idiomas disponíveis na implementação"),
    "iso.winpe_language_packs_count": (".cab", ".cab", ".cab", ".cab"),
    "iso.winpe_language_packs_path": ("Pfad", "Ruta", "Percorso", "Caminho"),
    "iso.winpe_language_packs_progress": ("Sprachpakete werden hochgeladen…", "Subiendo paquetes de idioma…", "Caricamento language pack…", "A enviar pacotes de idioma…"),
    "iso.winpe_language_packs_empty": ("Keine Pakete — das Sprachmenü beim Deploy bleibt leer, bis .cab-Dateien hochgeladen sind.", "Sin paquetes — el menú de idioma del despliegue estará vacío hasta subir archivos .cab.", "Nessun pack — il menu lingua del deploy resta vuoto finché non caricate file .cab.", "Sem pacotes — o menu de idioma da implementação fica vazio até enviar ficheiros .cab."),
    "iso.winpe_utility_mode_notice": ("WinPE-Dienstmodus: nur WinPE-Boot-Dateien (insbesondere boot.wim) werden für diese Version verwaltet.", "Modo utilitario WinPE: solo se gestionan archivos de arranque WinPE (especialmente boot.wim) en esta versión.", "Modalità utility WinPE: solo i file di boot WinPE (soprattutto boot.wim) sono gestiti per questa versione.", "Modo utilitário WinPE: apenas ficheiros de arranque WinPE (especialmente boot.wim) são geridos nesta versão."),
    "iso.winpe_global_masters_detected": ("Erkannte globale Masters (persistent)", "Masters globales detectados (persistentes)", "Master globali rilevati (persistenti)", "Masters globais detetados (persistentes)"),
    "iso.winpe_family": ("Familie", "Familia", "Famiglia", "Família"),
    "iso.winpe_folder": ("Ordner", "Carpeta", "Cartella", "Pasta"),
    "iso.winpe_locale": ("Locale", "Configuración regional", "Locale", "Locale"),
    "iso.winpe_need_boot_wim": ("ISO extrahieren oder boot.wim hochladen, bevor install.wim konfiguriert wird.", "Extraiga la ISO o suba boot.wim antes de configurar install.wim.", "Estrarre l'ISO o caricare boot.wim prima di configurare install.wim.", "Extraia a ISO ou envie boot.wim antes de configurar install.wim."),
    "iso.winpe_not_windows": ("Nur für Windows-/WinPE-Versionen.", "Solo versiones Windows / WinPE.", "Solo versioni Windows / WinPE.", "Apenas versões Windows / WinPE."),
    "iso.winpe_wim_only": ("Datei muss eine .wim-Image sein.", "El archivo debe ser una imagen .wim.", "Il file deve essere un'immagine .wim.", "O ficheiro deve ser uma imagem .wim."),
    "iso.winpe_patch_queued": ("startnet.cmd wird injiziert (Celery) — in Kürze aktualisieren.", "Inyectando startnet.cmd (Celery) — actualice en un momento.", "Iniezione startnet.cmd (Celery) — aggiornare tra poco.", "A injetar startnet.cmd (Celery) — atualize em breve."),
    "iso.winpe_patch_stale": ("Image als aktiv markiert, aber startnet.cmd in DB nicht bestätigt — erneut « boot.wim patchen » und Celery-Logs prüfen.", "Imagen marcada activa pero startnet.cmd no confirmado en BD — pulse de nuevo « Parchear boot.wim » y revise logs Celery.", "Immagine segnata attiva ma startnet.cmd non confermato in DB — cliccare di nuovo « Patch boot.wim » e controllare log Celery.", "Imagem marcada ativa mas startnet.cmd não confirmado na BD — clique novamente « Aplicar patch boot.wim » e verifique logs Celery."),
    "iso.winpe_patch_done": ("startnet.cmd in boot.wim für das aktive Image gepatcht.", "startnet.cmd parcheado en boot.wim para la imagen activa.", "startnet.cmd patchato in boot.wim per l'immagine attiva.", "startnet.cmd aplicado em boot.wim para a imagem ativa."),
    "iso.winpe_upload_started": ("Datei empfangen — Abschluss im Hintergrund (Verschieben und Registrieren)…", "Archivo recibido — finalizando en segundo plano (mover y registrar)…", "File ricevuto — completamento in background (spostamento e registrazione)…", "Ficheiro recebido — a concluir em segundo plano (mover e registar)…"),
    "iso.winpe_upload_progress": ("install.wim wird gesendet…", "Enviando install.wim…", "Invio install.wim…", "A enviar install.wim…"),
    "iso.winpe_upload_finalize": ("Abschluss auf dem Server…", "Finalizando en el servidor…", "Finalizzazione sul server…", "A concluir no servidor…"),
    "iso.winpe_upload_done": ("install.wim gespeichert.", "install.wim guardado.", "install.wim salvato.", "install.wim guardado."),
    "iso.winpe_upload_error": ("install.wim-Upload fehlgeschlagen.", "Error al subir install.wim.", "Caricamento install.wim fallito.", "Falha no envio de install.wim."),
}
